In [1]:
import os

dataDir = '/net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/'

listFiles = os.listdir(dataDir)
listFiles

['sam2_ff_0N_000029.edf.ge5',
 'sam3_ff_230N_000300.edf.ge5',
 'sam1_ff_155N_000168.edf.ge5',
 'test_sam2_000121.edf.ge5',
 'sam1_ff_305N_000230.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000396.edf.ge5',
 'dark_after_000083.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000370.edf.ge5',
 'test_sam1_000208.edf.ge5',
 'dark_after_000114.edf.ge5',
 'sam2_ff_400N_000132.edf.ge5',
 'test_sam3_000273.edf.ge5',
 'dark_after_000095.edf.ge5',
 'dark_after_000237.edf.ge5',
 'sam2_ff_50N_000043.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000402.edf.ge5',
 'dark_before_000365.edf.ge5',
 'sam3_ff_230N_000301.edf.ge5',
 'sam2_ff_250N_000093.edf.ge5',
 'sam2_ff_125N_000060.edf.ge5',
 'dark_before_000227.edf.ge5',
 'test_sam1_000178.edf.ge5',
 'sam3_ff_215N_000295.edf.ge5',
 'test_Au_cube_000239.edf.ge5',
 'test_sam3_000351.edf.ge5',
 'sam1_ff_185N_000181.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000380.edf.ge5',
 'sam1_ff_245N_000206.edf.ge5',
 'dark_before_000304.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000406.edf.ge5',
 'sam2_ff_100N_0000

In [2]:
darkFilesList = []
darkFilesDict = {}

for fileString in listFiles:
    if fileString.startswith('dark_before'):
        # find the index of each dark before
        idx = int(fileString[12:18])
        #print(int(fileString[12:18]))
        darkFilesDict[idx] = fileString

darkFilesDict

{365: 'dark_before_000365.edf.ge5',
 227: 'dark_before_000227.edf.ge5',
 304: 'dark_before_000304.edf.ge5',
 209: 'dark_before_000209.edf.ge5',
 322: 'dark_before_000322.edf.ge5',
 185: 'dark_before_000185.edf.ge5',
 26: 'dark_before_000026.edf.ge5',
 359: 'dark_before_000359.edf.ge5',
 215: 'dark_before_000215.edf.ge5',
 140: 'dark_before_000140.edf.ge5',
 172: 'dark_before_000172.edf.ge5',
 346: 'dark_before_000346.edf.ge5',
 154: 'dark_before_000154.edf.ge5',
 221: 'dark_before_000221.edf.ge5',
 179: 'dark_before_000179.edf.ge5',
 191: 'dark_before_000191.edf.ge5',
 109: 'dark_before_000109.edf.ge5',
 137: 'dark_before_000137.edf.ge5',
 292: 'dark_before_000292.edf.ge5',
 52: 'dark_before_000052.edf.ge5',
 129: 'dark_before_000129.edf.ge5',
 280: 'dark_before_000280.edf.ge5',
 158: 'dark_before_000158.edf.ge5',
 274: 'dark_before_000274.edf.ge5',
 298: 'dark_before_000298.edf.ge5',
 124: 'dark_before_000124.edf.ge5',
 162: 'dark_before_000162.edf.ge5',
 84: 'dark_before_000084.edf.g

In [3]:
darkFilesDict

{365: 'dark_before_000365.edf.ge5',
 227: 'dark_before_000227.edf.ge5',
 304: 'dark_before_000304.edf.ge5',
 209: 'dark_before_000209.edf.ge5',
 322: 'dark_before_000322.edf.ge5',
 185: 'dark_before_000185.edf.ge5',
 26: 'dark_before_000026.edf.ge5',
 359: 'dark_before_000359.edf.ge5',
 215: 'dark_before_000215.edf.ge5',
 140: 'dark_before_000140.edf.ge5',
 172: 'dark_before_000172.edf.ge5',
 346: 'dark_before_000346.edf.ge5',
 154: 'dark_before_000154.edf.ge5',
 221: 'dark_before_000221.edf.ge5',
 179: 'dark_before_000179.edf.ge5',
 191: 'dark_before_000191.edf.ge5',
 109: 'dark_before_000109.edf.ge5',
 137: 'dark_before_000137.edf.ge5',
 292: 'dark_before_000292.edf.ge5',
 52: 'dark_before_000052.edf.ge5',
 129: 'dark_before_000129.edf.ge5',
 280: 'dark_before_000280.edf.ge5',
 158: 'dark_before_000158.edf.ge5',
 274: 'dark_before_000274.edf.ge5',
 298: 'dark_before_000298.edf.ge5',
 124: 'dark_before_000124.edf.ge5',
 162: 'dark_before_000162.edf.ge5',
 84: 'dark_before_000084.edf.g

In [4]:
darkFilesKeys = sorted(darkFilesDict)
darkFilesKeys

[20,
 26,
 33,
 40,
 46,
 52,
 58,
 64,
 70,
 72,
 78,
 84,
 90,
 96,
 103,
 109,
 116,
 124,
 129,
 137,
 140,
 146,
 150,
 154,
 158,
 162,
 166,
 172,
 179,
 185,
 191,
 197,
 203,
 209,
 215,
 221,
 227,
 233,
 241,
 246,
 250,
 253,
 256,
 259,
 262,
 265,
 268,
 274,
 280,
 286,
 292,
 298,
 304,
 310,
 316,
 322,
 328,
 334,
 340,
 346,
 352,
 359,
 365]

In [5]:
sam1FilesList = []
sam1FilesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('sam1_ff'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        sam1FilesDict4Idx[fileString] = idx
#         idx = int(fileString[12:18])
#         #print(int(fileString[12:18]))
#         darkFilesDict[idx] = fileString
#         darkFiles.append(fileString)

# 
sam1FilesDict4Idx 

{'sam1_ff_155N_000168.edf.ge5': 168,
 'sam1_ff_305N_000230.edf.ge5': 230,
 'sam1_ff_185N_000181.edf.ge5': 181,
 'sam1_ff_245N_000206.edf.ge5': 206,
 'sam1_ff_170N_000174.edf.ge5': 174,
 'sam1_ff_200N_000187.edf.ge5': 187,
 'sam1_ff_245N_000205.edf.ge5': 205,
 'sam1_ff_50N_000147.edf.ge5': 147,
 'sam1_ff_185N_000182.edf.ge5': 182,
 'sam1_ff_305N_000229.edf.ge5': 229,
 'sam1_ff_140N_000163.edf.ge5': 163,
 'sam1_ff_320N_000234.edf.ge5': 234,
 'sam1_ff_185N_000180.edf.ge5': 180,
 'sam1_ff_230N_000200.edf.ge5': 200,
 'sam1_ff_155N_000169.edf.ge5': 169,
 'sam1_ff_260N_000210.edf.ge5': 210,
 'sam1_ff_290N_000224.edf.ge5': 224,
 'sam1_ff_290N_000223.edf.ge5': 223,
 'sam1_ff_230N_000198.edf.ge5': 198,
 'sam1_ff_100N_000155.edf.ge5': 155,
 'sam1_ff_25N_000141.edf.ge5': 141,
 'sam1_ff_75N_000151.edf.ge5': 151,
 'sam1_ff_275N_000218.edf.ge5': 218,
 'sam1_ff_170N_000173.edf.ge5': 173,
 'sam1_ff_215N_000193.edf.ge5': 193,
 'sam1_ff_215N_000192.edf.ge5': 192,
 'sam1_ff_290N_000222.edf.ge5': 222,
 'sa

In [6]:
# next is to find the dark files for each file
darkFilesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('sam1_ff'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        # next is to find the corresponding dark file
        for darkKey in darkFilesKeys:
            if darkKey >= idx:
                print(str(idx) + "-" + str(darkKey))
                darkFilesDict4Idx[fileString] = darkFilesDict[darkKey]
                break

darkFilesDict4Idx

168-172
230-233
181-185
206-209
174-179
187-191
205-209
147-150
182-185
229-233
163-166
234-241
180-185
200-203
169-172
210-215
224-227
223-227
198-203
155-158
141-146
151-154
218-221
173-179
193-197
192-197
222-227
228-233
204-209
194-197
159-162
199-203
138-140
235-241
186-191
175-179
167-172
211-215
212-215
216-221
188-191
236-241
217-221


{'sam1_ff_155N_000168.edf.ge5': 'dark_before_000172.edf.ge5',
 'sam1_ff_305N_000230.edf.ge5': 'dark_before_000233.edf.ge5',
 'sam1_ff_185N_000181.edf.ge5': 'dark_before_000185.edf.ge5',
 'sam1_ff_245N_000206.edf.ge5': 'dark_before_000209.edf.ge5',
 'sam1_ff_170N_000174.edf.ge5': 'dark_before_000179.edf.ge5',
 'sam1_ff_200N_000187.edf.ge5': 'dark_before_000191.edf.ge5',
 'sam1_ff_245N_000205.edf.ge5': 'dark_before_000209.edf.ge5',
 'sam1_ff_50N_000147.edf.ge5': 'dark_before_000150.edf.ge5',
 'sam1_ff_185N_000182.edf.ge5': 'dark_before_000185.edf.ge5',
 'sam1_ff_305N_000229.edf.ge5': 'dark_before_000233.edf.ge5',
 'sam1_ff_140N_000163.edf.ge5': 'dark_before_000166.edf.ge5',
 'sam1_ff_320N_000234.edf.ge5': 'dark_before_000241.edf.ge5',
 'sam1_ff_185N_000180.edf.ge5': 'dark_before_000185.edf.ge5',
 'sam1_ff_230N_000200.edf.ge5': 'dark_before_000203.edf.ge5',
 'sam1_ff_155N_000169.edf.ge5': 'dark_before_000172.edf.ge5',
 'sam1_ff_260N_000210.edf.ge5': 'dark_before_000215.edf.ge5',
 'sam1_ff

In [7]:
len(darkFilesDict4Idx)

43

In [8]:
# now start to convert ge5 files to patches
from src.datasets.ge2patch import *

In [10]:
pwd

'/home/beams0/WZHENG/EventDetection/rareEventHEDM_v1'

In [12]:
# need to create the following dir first
outDir = '../kasemer_sam1_patch_dir/'

i = 1

for key in darkFilesDict4Idx:
    print(f"Reading dark file from {dataDir+darkFilesDict4Idx[key]} ... ")
    dark = ge_raw2array(dataDir+darkFilesDict4Idx[key], skip_frm=0).mean(axis=0).astype(np.float32)
    print(f"Done with reading dark file from {dataDir+darkFilesDict4Idx[key]} with {dark}")
    print(f"The input file is {key}")
    outFile = outDir + key[:-3] + "h5"
    print(f"The output file is {outFile}")
    print(f"Start to generate patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    ge_raw2patch(gefname=dataDir+key, ofn=outFile, dark=dark, 
                 bkgd=100, psz=15, skip_frm=0, min_intensity=0, max_r=None)
    print(f"Done generating patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    i += 1

Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000172.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000172.edf.ge5 with [[1646.2 1654.6 1653.5 ... 1830.2 1829.4 1825.6]
 [1665.9 1670.4 1670.1 ... 1822.5 1819.7 1819.4]
 [1675.9 1678.9 1676.8 ... 1829.1 1832.1 1827.4]
 ...
 [1676.  1677.  1677.  ... 1733.4 1731.6 1732.1]
 [1669.2 1667.9 1669.4 ... 1727.6 1727.7 1725.3]
 [1633.4 1631.9 1630.8 ... 1696.8 1696.1 1698. ]]
The input file is sam1_ff_155N_000168.edf.ge5
The output file is ../kasemer_sam1_patch_dir/sam1_ff_155N_000168.edf.h5
Start to generate patches for file sam1_ff_155N_000168.edf.ge5 (1/43)...
82571 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam1_ff_155N_000168.edf.ge5, 0 are too big.
Done generating patches for file sam1_ff_155N_000168.edf.ge5 (1/43)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data

73866 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam1_ff_185N_000182.edf.ge5, 0 are too big.
Done generating patches for file sam1_ff_185N_000182.edf.ge5 (9/43)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000233.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000233.edf.ge5 with [[1646.3 1654.1 1655.7 ... 1830.6 1829.7 1826.7]
 [1666.7 1670.4 1668.8 ... 1822.  1821.  1819.6]
 [1675.2 1679.6 1676.6 ... 1829.9 1830.5 1828.6]
 ...
 [1675.2 1677.4 1677.4 ... 1734.6 1732.7 1730.8]
 [1668.8 1667.8 1668.7 ... 1728.  1727.4 1724.4]
 [1632.7 1632.  1630.1 ... 1698.  1696.3 1696.6]]
The input file is sam1_ff_305N_000229.edf.ge5
The output file is ../kasemer_sam1_patch_dir/sam1_ff_305N_000229.edf.h5
Start to generate patches for file sam1_ff_305N_000229.edf.ge5 (10/43)...
83758 patches of size 15 cropped from /net/wolf/data/tomo1/ka

81974 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam1_ff_290N_000223.edf.ge5, 0 are too big.
Done generating patches for file sam1_ff_290N_000223.edf.ge5 (18/43)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000203.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000203.edf.ge5 with [[1646.3 1654.3 1654.  ... 1831.6 1829.6 1825.6]
 [1666.4 1671.4 1669.1 ... 1822.3 1821.  1819.8]
 [1675.4 1679.6 1676.8 ... 1830.2 1831.  1828.3]
 ...
 [1676.6 1677.3 1678.8 ... 1734.4 1733.  1731. ]
 [1669.9 1667.6 1669.5 ... 1728.6 1727.3 1724.8]
 [1632.1 1631.7 1631.2 ... 1698.9 1696.8 1696.9]]
The input file is sam1_ff_230N_000198.edf.ge5
The output file is ../kasemer_sam1_patch_dir/sam1_ff_230N_000198.edf.h5
Start to generate patches for file sam1_ff_230N_000198.edf.ge5 (19/43)...
98977 patches of size 15 cropped from /net/wolf/data/tomo1/k

81368 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam1_ff_290N_000222.edf.ge5, 0 are too big.
Done generating patches for file sam1_ff_290N_000222.edf.ge5 (27/43)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000233.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000233.edf.ge5 with [[1646.3 1654.1 1655.7 ... 1830.6 1829.7 1826.7]
 [1666.7 1670.4 1668.8 ... 1822.  1821.  1819.6]
 [1675.2 1679.6 1676.6 ... 1829.9 1830.5 1828.6]
 ...
 [1675.2 1677.4 1677.4 ... 1734.6 1732.7 1730.8]
 [1668.8 1667.8 1668.7 ... 1728.  1727.4 1724.4]
 [1632.7 1632.  1630.1 ... 1698.  1696.3 1696.6]]
The input file is sam1_ff_305N_000228.edf.ge5
The output file is ../kasemer_sam1_patch_dir/sam1_ff_305N_000228.edf.h5
Start to generate patches for file sam1_ff_305N_000228.edf.ge5 (28/43)...
82415 patches of size 15 cropped from /net/wolf/data/tomo1/k

84345 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam1_ff_170N_000175.edf.ge5, 0 are too big.
Done generating patches for file sam1_ff_170N_000175.edf.ge5 (36/43)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000172.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000172.edf.ge5 with [[1646.2 1654.6 1653.5 ... 1830.2 1829.4 1825.6]
 [1665.9 1670.4 1670.1 ... 1822.5 1819.7 1819.4]
 [1675.9 1678.9 1676.8 ... 1829.1 1832.1 1827.4]
 ...
 [1676.  1677.  1677.  ... 1733.4 1731.6 1732.1]
 [1669.2 1667.9 1669.4 ... 1727.6 1727.7 1725.3]
 [1633.4 1631.9 1630.8 ... 1696.8 1696.1 1698. ]]
The input file is sam1_ff_155N_000167.edf.ge5
The output file is ../kasemer_sam1_patch_dir/sam1_ff_155N_000167.edf.h5
Start to generate patches for file sam1_ff_155N_000167.edf.ge5 (37/43)...
82582 patches of size 15 cropped from /net/wolf/data/tomo1/k