In [1]:
import os

dataDir = '/net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/'

listFiles = os.listdir(dataDir)
listFiles

['sam2_ff_0N_000029.edf.ge5',
 'sam3_ff_230N_000300.edf.ge5',
 'sam1_ff_155N_000168.edf.ge5',
 'test_sam2_000121.edf.ge5',
 'sam1_ff_305N_000230.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000396.edf.ge5',
 'dark_after_000083.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000370.edf.ge5',
 'test_sam1_000208.edf.ge5',
 'dark_after_000114.edf.ge5',
 'sam2_ff_400N_000132.edf.ge5',
 'test_sam3_000273.edf.ge5',
 'dark_after_000095.edf.ge5',
 'dark_after_000237.edf.ge5',
 'sam2_ff_50N_000043.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000402.edf.ge5',
 'dark_before_000365.edf.ge5',
 'sam3_ff_230N_000301.edf.ge5',
 'sam2_ff_250N_000093.edf.ge5',
 'sam2_ff_125N_000060.edf.ge5',
 'dark_before_000227.edf.ge5',
 'test_sam1_000178.edf.ge5',
 'sam3_ff_215N_000295.edf.ge5',
 'test_Au_cube_000239.edf.ge5',
 'test_sam3_000351.edf.ge5',
 'sam1_ff_185N_000181.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000380.edf.ge5',
 'sam1_ff_245N_000206.edf.ge5',
 'dark_before_000304.edf.ge5',
 'kasemer_Au_cubes_ff_dt_000406.edf.ge5',
 'sam2_ff_100N_0000

In [2]:
darkFilesList = []
darkFilesDict = {}

for fileString in listFiles:
    if fileString.startswith('dark_before'):
        # find the index of each dark before
        idx = int(fileString[12:18])
        #print(int(fileString[12:18]))
        darkFilesDict[idx] = fileString

darkFilesDict

{365: 'dark_before_000365.edf.ge5',
 227: 'dark_before_000227.edf.ge5',
 304: 'dark_before_000304.edf.ge5',
 209: 'dark_before_000209.edf.ge5',
 322: 'dark_before_000322.edf.ge5',
 185: 'dark_before_000185.edf.ge5',
 26: 'dark_before_000026.edf.ge5',
 359: 'dark_before_000359.edf.ge5',
 215: 'dark_before_000215.edf.ge5',
 140: 'dark_before_000140.edf.ge5',
 172: 'dark_before_000172.edf.ge5',
 346: 'dark_before_000346.edf.ge5',
 154: 'dark_before_000154.edf.ge5',
 221: 'dark_before_000221.edf.ge5',
 179: 'dark_before_000179.edf.ge5',
 191: 'dark_before_000191.edf.ge5',
 109: 'dark_before_000109.edf.ge5',
 137: 'dark_before_000137.edf.ge5',
 292: 'dark_before_000292.edf.ge5',
 52: 'dark_before_000052.edf.ge5',
 129: 'dark_before_000129.edf.ge5',
 280: 'dark_before_000280.edf.ge5',
 158: 'dark_before_000158.edf.ge5',
 274: 'dark_before_000274.edf.ge5',
 298: 'dark_before_000298.edf.ge5',
 124: 'dark_before_000124.edf.ge5',
 162: 'dark_before_000162.edf.ge5',
 84: 'dark_before_000084.edf.g

In [3]:
darkFilesKeys = sorted(darkFilesDict)
darkFilesKeys

[20,
 26,
 33,
 40,
 46,
 52,
 58,
 64,
 70,
 72,
 78,
 84,
 90,
 96,
 103,
 109,
 116,
 124,
 129,
 137,
 140,
 146,
 150,
 154,
 158,
 162,
 166,
 172,
 179,
 185,
 191,
 197,
 203,
 209,
 215,
 221,
 227,
 233,
 241,
 246,
 250,
 253,
 256,
 259,
 262,
 265,
 268,
 274,
 280,
 286,
 292,
 298,
 304,
 310,
 316,
 322,
 328,
 334,
 340,
 346,
 352,
 359,
 365]

In [4]:
sam3FilesList = []
sam3FilesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('sam3_ff'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        sam3FilesDict4Idx[fileString] = idx
#         idx = int(fileString[12:18])
#         #print(int(fileString[12:18]))
#         darkFilesDict[idx] = fileString
#         darkFiles.append(fileString)

# 
sam3FilesDict4Idx 

{'sam3_ff_230N_000300.edf.ge5': 300,
 'sam3_ff_230N_000301.edf.ge5': 301,
 'sam3_ff_215N_000295.edf.ge5': 295,
 'sam3_ff_245N_000306.edf.ge5': 306,
 'sam3_ff_305N_000331.edf.ge5': 331,
 'sam3_ff_305N_000329.edf.ge5': 329,
 'sam3_ff_260N_000311.edf.ge5': 311,
 'sam3_ff1_000022.edf.ge5': 22,
 'sam3_ff_290N_000324.edf.ge5': 324,
 'sam3_ff_140N_000266.edf.ge5': 266,
 'sam3_ff_350N_000347.edf.ge5': 347,
 'sam3_ff_185N_000283.edf.ge5': 283,
 'sam3_ff_335N_000343.edf.ge5': 343,
 'sam3_ff_125N_000263.edf.ge5': 263,
 'sam3_ff_155N_000270.edf.ge5': 270,
 'sam3_ff_290N_000325.edf.ge5': 325,
 'sam3_ff_260N_000313.edf.ge5': 313,
 'sam3_ff_185N_000281.edf.ge5': 281,
 'sam3_ff1_000023.edf.ge5': 23,
 'sam3_ff_25N_000251.edf.ge5': 251,
 'sam3_ff_275N_000317.edf.ge5': 317,
 'sam3_ff_320N_000336.edf.ge5': 336,
 'sam3_ff_50N_000254.edf.ge5': 254,
 'sam3_ff_75N_000257.edf.ge5': 257,
 'sam3_ff_230N_000299.edf.ge5': 299,
 'sam3_ff_350N_000349.edf.ge5': 349,
 'sam3_ff_215N_000294.edf.ge5': 294,
 'sam3_ff_215N

In [5]:
# next is to find the dark files for each file
darkFilesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('sam3_ff'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        # next is to find the corresponding dark file
        for darkKey in darkFilesKeys:
            if darkKey >= idx:
                print(str(idx) + "-" + str(darkKey))
                darkFilesDict4Idx[fileString] = darkFilesDict[darkKey]
                break

darkFilesDict4Idx

300-304
301-304
295-298
306-310
331-334
329-334
311-316
22-26
324-328
266-268
347-352
283-286
343-346
263-265
270-274
325-328
313-316
281-286
23-26
251-253
317-322
336-340
254-256
257-259
299-304
349-352
294-298
293-298
288-292
337-340
307-310
354-359
353-359
247-250
289-292
21-26
287-292
312-316
348-352
276-280
260-262
319-322
275-280
282-286
355-359
342-346
305-310
277-280
335-340
269-274
271-274
330-334
323-328
341-346
318-322


{'sam3_ff_230N_000300.edf.ge5': 'dark_before_000304.edf.ge5',
 'sam3_ff_230N_000301.edf.ge5': 'dark_before_000304.edf.ge5',
 'sam3_ff_215N_000295.edf.ge5': 'dark_before_000298.edf.ge5',
 'sam3_ff_245N_000306.edf.ge5': 'dark_before_000310.edf.ge5',
 'sam3_ff_305N_000331.edf.ge5': 'dark_before_000334.edf.ge5',
 'sam3_ff_305N_000329.edf.ge5': 'dark_before_000334.edf.ge5',
 'sam3_ff_260N_000311.edf.ge5': 'dark_before_000316.edf.ge5',
 'sam3_ff1_000022.edf.ge5': 'dark_before_000026.edf.ge5',
 'sam3_ff_290N_000324.edf.ge5': 'dark_before_000328.edf.ge5',
 'sam3_ff_140N_000266.edf.ge5': 'dark_before_000268.edf.ge5',
 'sam3_ff_350N_000347.edf.ge5': 'dark_before_000352.edf.ge5',
 'sam3_ff_185N_000283.edf.ge5': 'dark_before_000286.edf.ge5',
 'sam3_ff_335N_000343.edf.ge5': 'dark_before_000346.edf.ge5',
 'sam3_ff_125N_000263.edf.ge5': 'dark_before_000265.edf.ge5',
 'sam3_ff_155N_000270.edf.ge5': 'dark_before_000274.edf.ge5',
 'sam3_ff_290N_000325.edf.ge5': 'dark_before_000328.edf.ge5',
 'sam3_ff_26

In [6]:
len(darkFilesDict4Idx)

55

In [7]:
# now start to convert ge5 files to patches
from src.datasets.ge2patch import *

In [9]:
# need to create the following dir first
outDir = '../kasemer_sam3_patch_dir/'

i = 1

for key in darkFilesDict4Idx:
    print(f"Reading dark file from {dataDir+darkFilesDict4Idx[key]} ... ")
    dark = ge_raw2array(dataDir+darkFilesDict4Idx[key], skip_frm=0).mean(axis=0).astype(np.float32)
    print(f"Done with reading dark file from {dataDir+darkFilesDict4Idx[key]} with {dark}")
    print(f"The input file is {key}")
    outFile = outDir + key[:-3] + "h5"
    print(f"The output file is {outFile}")
    print(f"Start to generate patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    ge_raw2patch(gefname=dataDir+key, ofn=outFile, dark=dark, 
                 bkgd=100, psz=15, skip_frm=0, min_intensity=0, max_r=None)
    print(f"Done generating patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    i += 1

Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000304.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000304.edf.ge5 with [[1646.3 1654.1 1653.9 ... 1830.7 1828.9 1826.8]
 [1666.8 1670.6 1668.6 ... 1822.2 1822.1 1819.4]
 [1675.1 1679.7 1677.2 ... 1829.9 1832.  1828.4]
 ...
 [1676.  1677.3 1678.1 ... 1734.6 1731.7 1731.7]
 [1669.1 1667.3 1668.2 ... 1727.8 1727.9 1725.6]
 [1633.2 1631.8 1630.8 ... 1697.1 1697.  1696.7]]
The input file is sam3_ff_230N_000300.edf.ge5
The output file is ../kasemer_sam3_patch_dir/sam3_ff_230N_000300.edf.h5
Start to generate patches for file sam3_ff_230N_000300.edf.ge5 (1/55)...
100226 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam3_ff_230N_000300.edf.ge5, 0 are too big.
Done generating patches for file sam3_ff_230N_000300.edf.ge5 (1/55)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_dat

KeyboardInterrupt: 

99222 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam3_ff_215N_000294.edf.ge5, 0 are too big.
Done generating patches for file sam3_ff_215N_000294.edf.ge5 (27/55)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000298.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000298.edf.ge5 with [[1646.1 1655.1 1654.3 ... 1831.2 1829.3 1825.8]
 [1666.4 1671.2 1669.4 ... 1822.2 1821.6 1819.7]
 [1675.4 1679.8 1677.4 ... 1830.1 1831.9 1828.3]
 ...
 [1675.6 1677.  1678.5 ... 1735.  1733.5 1731.7]
 [1669.5 1667.8 1669.1 ... 1727.1 1727.3 1724.8]
 [1632.9 1632.2 1630.  ... 1697.9 1697.  1697.4]]
The input file is sam3_ff_215N_000293.edf.ge5
The output file is ../kasemer_sam3_patch_dir/sam3_ff_215N_000293.edf.h5
Start to generate patches for file sam3_ff_215N_000293.edf.ge5 (28/55)...
99871 patches of size 15 cropped from /net/wolf/data/tomo1/k

71837 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam3_ff1_000021.edf.ge5, 0 are too big.
Done generating patches for file sam3_ff1_000021.edf.ge5 (36/55)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000292.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000292.edf.ge5 with [[1646.2 1654.1 1655.3 ... 1832.1 1829.  1825.9]
 [1665.8 1671.5 1670.2 ... 1822.4 1821.6 1819.5]
 [1675.  1680.2 1677.6 ... 1829.2 1831.3 1828.9]
 ...
 [1676.4 1677.7 1679.3 ... 1734.5 1733.1 1731.6]
 [1669.9 1667.8 1669.5 ... 1728.6 1728.4 1725.1]
 [1633.  1632.1 1631.1 ... 1697.7 1696.5 1697.2]]
The input file is sam3_ff_200N_000287.edf.ge5
The output file is ../kasemer_sam3_patch_dir/sam3_ff_200N_000287.edf.h5
Start to generate patches for file sam3_ff_200N_000287.edf.ge5 (37/55)...
102031 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_

33033 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam3_ff_365N_000355.edf.ge5, 2051 are too big.
Done generating patches for file sam3_ff_365N_000355.edf.ge5 (45/55)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000346.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000346.edf.ge5 with [[1646.1 1654.9 1653.9 ... 1830.8 1828.8 1825.8]
 [1665.8 1670.6 1668.2 ... 1822.1 1821.4 1819.5]
 [1675.2 1679.4 1676.2 ... 1830.6 1831.5 1828.5]
 ...
 [1675.1 1676.9 1677.7 ... 1733.6 1732.2 1731.5]
 [1669.3 1667.2 1669.  ... 1726.7 1727.7 1724.8]
 [1631.8 1631.6 1630.1 ... 1697.3 1696.1 1697.3]]
The input file is sam3_ff_335N_000342.edf.ge5
The output file is ../kasemer_sam3_patch_dir/sam3_ff_335N_000342.edf.h5
Start to generate patches for file sam3_ff_335N_000342.edf.ge5 (46/55)...
80193 patches of size 15 cropped from /net/wolf/data/tomo

82760 patches of size 15 cropped from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/sam3_ff_335N_000341.edf.ge5, 749 are too big.
Done generating patches for file sam3_ff_335N_000341.edf.ge5 (54/55)...
Reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000322.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/kasemer_jun22_data/kasemer_jun22/ge5/dark_before_000322.edf.ge5 with [[1646.  1655.  1654.7 ... 1831.5 1830.2 1826.4]
 [1666.4 1670.6 1669.8 ... 1821.7 1820.9 1819.6]
 [1675.6 1679.  1675.6 ... 1830.  1830.5 1828.4]
 ...
 [1676.3 1676.3 1678.9 ... 1734.1 1732.8 1730.9]
 [1669.4 1667.4 1669.1 ... 1727.9 1728.3 1724.2]
 [1633.3 1632.2 1631.2 ... 1697.7 1696.2 1697.9]]
The input file is sam3_ff_275N_000318.edf.ge5
The output file is ../kasemer_sam3_patch_dir/sam3_ff_275N_000318.edf.h5
Start to generate patches for file sam3_ff_275N_000318.edf.ge5 (55/55)...
122205 patches of size 15 cropped from /net/wolf/data/tomo