In [12]:
import os

dataDir = '/net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/'

listFiles = os.listdir(dataDir)
listFiles

['park_ss_ff_90MPa_unload_000631.edf.ge5',
 'ac_s2_linescan_000835.edf.ge5',
 'park_ss_ff_000262.edf.ge5',
 'ac_s6_linescan_001570.edf.ge5',
 'ac_s14_linescan_001942.edf.ge5',
 'ac_s4_linescan_001038.edf.ge5',
 'park_ss_ff_90MPa_unload_000624.edf.ge5',
 'ac_s11_linescan_001636.edf.ge5',
 'ac_s8_linescan_001282.edf.ge5',
 'ac_s8_linescan_001348.edf.ge5',
 'ac_s6_linescan_001587.edf.ge5',
 'ac_s4_linescan_001028.edf.ge5',
 'park_ss_ff_hedm_resolution_250MPa_2_000477.edf.ge5',
 'ac_s8_linescan_001292.edf.ge5',
 'ac_s6_linescan_001603.edf.ge5',
 'ac_s6_linescan_001590.edf.ge5',
 'ac_s14_linescan_001913.edf.ge5',
 'ac_s10_linescan_002006.edf.ge5',
 'dark_after_000680.edf.ge5',
 'ac_s14_linescan_001886.edf.ge5',
 'park_ss_ff_000247.edf.ge5',
 'ac_s6_linescan_001553.edf.ge5',
 'ac_s1_linescan_001158.edf.ge5',
 'ac_s6_linescan_001585.edf.ge5',
 'ac_s6_linescan_001548.edf.ge5',
 'ac_s10_linescan_001982.edf.ge5',
 'ac_s3_linescan_000944.edf.ge5',
 'air_5s_000754.edf.ge5',
 'dark_after_000569.edf

In [24]:
listFiles.sort(key=lambda f: int(filter(str.isdigit, f)))

[]

In [2]:
darkFilesList = []
darkFilesDict = {}

for fileString in listFiles:
    if fileString.startswith('dark_before'):
        # find the index of each dark before
        idx = int(fileString[12:18])
        #print(int(fileString[12:18]))
        darkFilesDict[idx] = fileString

darkFilesDict

{485: 'dark_before_000485.edf.ge5',
 1875: 'dark_before_001875.edf.ge5',
 87: 'dark_before_000087.edf.ge5',
 461: 'dark_before_000461.edf.ge5',
 365: 'dark_before_000365.edf.ge5',
 651: 'dark_before_000651.edf.ge5',
 482: 'dark_before_000482.edf.ge5',
 368: 'dark_before_000368.edf.ge5',
 1430: 'dark_before_001430.edf.ge5',
 320: 'dark_before_000320.edf.ge5',
 467: 'dark_before_000467.edf.ge5',
 251: 'dark_before_000251.edf.ge5',
 1523: 'dark_before_001523.edf.ge5',
 452: 'dark_before_000452.edf.ge5',
 422: 'dark_before_000422.edf.ge5',
 576: 'dark_before_000576.edf.ge5',
 371: 'dark_before_000371.edf.ge5',
 440: 'dark_before_000440.edf.ge5',
 729: 'dark_before_000729.edf.ge5',
 645: 'dark_before_000645.edf.ge5',
 359: 'dark_before_000359.edf.ge5',
 690: 'dark_before_000690.edf.ge5',
 362: 'dark_before_000362.edf.ge5',
 329: 'dark_before_000329.edf.ge5',
 491: 'dark_before_000491.edf.ge5',
 693: 'dark_before_000693.edf.ge5',
 675: 'dark_before_000675.edf.ge5',
 299: 'dark_before_000299.

In [3]:
darkFilesDict

{485: 'dark_before_000485.edf.ge5',
 1875: 'dark_before_001875.edf.ge5',
 87: 'dark_before_000087.edf.ge5',
 461: 'dark_before_000461.edf.ge5',
 365: 'dark_before_000365.edf.ge5',
 651: 'dark_before_000651.edf.ge5',
 482: 'dark_before_000482.edf.ge5',
 368: 'dark_before_000368.edf.ge5',
 1430: 'dark_before_001430.edf.ge5',
 320: 'dark_before_000320.edf.ge5',
 467: 'dark_before_000467.edf.ge5',
 251: 'dark_before_000251.edf.ge5',
 1523: 'dark_before_001523.edf.ge5',
 452: 'dark_before_000452.edf.ge5',
 422: 'dark_before_000422.edf.ge5',
 576: 'dark_before_000576.edf.ge5',
 371: 'dark_before_000371.edf.ge5',
 440: 'dark_before_000440.edf.ge5',
 729: 'dark_before_000729.edf.ge5',
 645: 'dark_before_000645.edf.ge5',
 359: 'dark_before_000359.edf.ge5',
 690: 'dark_before_000690.edf.ge5',
 362: 'dark_before_000362.edf.ge5',
 329: 'dark_before_000329.edf.ge5',
 491: 'dark_before_000491.edf.ge5',
 693: 'dark_before_000693.edf.ge5',
 675: 'dark_before_000675.edf.ge5',
 299: 'dark_before_000299.

In [4]:
darkFilesKeys = sorted(darkFilesDict)
darkFilesKeys

[87,
 245,
 251,
 257,
 266,
 281,
 287,
 293,
 296,
 299,
 302,
 305,
 308,
 311,
 314,
 320,
 329,
 344,
 347,
 350,
 353,
 356,
 359,
 362,
 365,
 368,
 371,
 374,
 377,
 383,
 392,
 398,
 404,
 410,
 416,
 422,
 428,
 434,
 437,
 440,
 443,
 446,
 449,
 452,
 455,
 461,
 467,
 473,
 476,
 479,
 482,
 485,
 488,
 491,
 496,
 502,
 508,
 514,
 523,
 529,
 535,
 543,
 549,
 555,
 561,
 567,
 570,
 573,
 576,
 579,
 582,
 585,
 588,
 591,
 594,
 597,
 600,
 603,
 606,
 609,
 615,
 621,
 627,
 633,
 639,
 645,
 648,
 651,
 654,
 657,
 660,
 663,
 666,
 669,
 672,
 675,
 678,
 681,
 684,
 687,
 690,
 693,
 696,
 699,
 702,
 705,
 708,
 711,
 714,
 717,
 720,
 723,
 726,
 729,
 732,
 735,
 738,
 741,
 744,
 747,
 750,
 758,
 771,
 792,
 880,
 913,
 1005,
 1086,
 1179,
 1258,
 1351,
 1430,
 1523,
 1616,
 1699,
 1791,
 1875,
 1970]

In [5]:
parkFilesList = []
parkFilesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('park_ss_ff'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        parkFilesDict4Idx[fileString] = idx
#         idx = int(fileString[12:18])
#         #print(int(fileString[12:18]))
#         darkFilesDict[idx] = fileString
#         darkFiles.append(fileString)

# 
parkFilesDict4Idx 

{'park_ss_ff_90MPa_unload_000631.edf.ge5': 631,
 'park_ss_ff_000262.edf.ge5': 262,
 'park_ss_ff_90MPa_unload_000624.edf.ge5': 624,
 'park_ss_ff_hedm_resolution_250MPa_2_000477.edf.ge5': 477,
 'park_ss_ff_000247.edf.ge5': 247,
 'park_ss_ff_280MPa_000533.edf.ge5': 533,
 'park_ss_ff_0MPa_000335.edf.ge5': 335,
 'park_ss_ff_ome_offset_0MPa_unload_000724.edf.ge5': 724,
 'park_ss_ff_000269.edf.ge5': 269,
 'park_ss_ff_100MPa_000396.edf.ge5': 396,
 'park_ss_ff_270MPa_000518.edf.ge5': 518,
 'park_ss_ff_hedm_resolution_0MPa_unload_000673.edf.ge5': 673,
 'park_ss_ff_230MPa_000425.edf.ge5': 425,
 'park_ss_ff_270MPa_000517.edf.ge5': 517,
 'park_ss_ff_0MPa_000318.edf.ge5': 318,
 'park_ss_ff_240MPa_000458.edf.ge5': 458,
 'park_ss_ff_hedm_resolution_235MPa_000447.edf.ge5': 447,
 'park_ss_ff_0MPa_000341.edf.ge5': 341,
 'park_ss_ff_235MPa_000431.edf.ge5': 431,
 'park_ss_ff_280MPa_000531.edf.ge5': 531,
 'park_ss_ff_50MPa_000385.edf.ge5': 385,
 'park_ss_ff_hedm_resolution_290MPa_000589.edf.ge5': 589,
 'par

In [6]:
# next is to find the dark files for each file
darkFilesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('park_ss_ff'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        # next is to find the corresponding dark file
        for darkKey in darkFilesKeys:
            if darkKey >= idx:
                print(str(idx) + "-" + str(darkKey))
                darkFilesDict4Idx[fileString] = darkFilesDict[darkKey]
                break

darkFilesDict4Idx

631-633
262-266
624-627
477-479
247-251
533-535
335-344
724-726
269-281
396-398
518-523
673-675
425-428
517-523
318-320
458-461
447-449
341-344
431-434
531-535
385-392
589-591
628-633
435-437
459-461
486-488
260-266
462-467
636-639
545-549
700-702
574-576
623-627
703-705
254-257
316-320
556-561
411-416
420-422
258-266
317-320
303-305
379-383
369-371
658-660
315-320
706-708
405-410
503-508
253-257
278-281
406-410
712-714
676-678
378-383
394-398
413-416
611-615
270-281
492-496
288-293
402-404
470-473
450-452
390-392
285-287
649-651
324-329
563-567
395-398
300-302
586-588
279-281
372-374
751-758
468-473
515-523
444-446
424-428
527-529
480-482
340-344
580-582
733-735
745-747
261-266
275-281
646-648
271-281
463-467
438-440
509-514
592-594
694-696
387-392
309-311
326-329
337-344
325-329
321-329
419-422
348-350
661-663
465-467
388-392
536-543
511-514
274-281
721-723
267-281
739-741
679-681
532-535
558-561
423-428
252-257
562-567
430-434
426-428
432-434
268-281
616-621
612-615
577-579
685-687


{'park_ss_ff_90MPa_unload_000631.edf.ge5': 'dark_before_000633.edf.ge5',
 'park_ss_ff_000262.edf.ge5': 'dark_before_000266.edf.ge5',
 'park_ss_ff_90MPa_unload_000624.edf.ge5': 'dark_before_000627.edf.ge5',
 'park_ss_ff_hedm_resolution_250MPa_2_000477.edf.ge5': 'dark_before_000479.edf.ge5',
 'park_ss_ff_000247.edf.ge5': 'dark_before_000251.edf.ge5',
 'park_ss_ff_280MPa_000533.edf.ge5': 'dark_before_000535.edf.ge5',
 'park_ss_ff_0MPa_000335.edf.ge5': 'dark_before_000344.edf.ge5',
 'park_ss_ff_ome_offset_0MPa_unload_000724.edf.ge5': 'dark_before_000726.edf.ge5',
 'park_ss_ff_000269.edf.ge5': 'dark_before_000281.edf.ge5',
 'park_ss_ff_100MPa_000396.edf.ge5': 'dark_before_000398.edf.ge5',
 'park_ss_ff_270MPa_000518.edf.ge5': 'dark_before_000523.edf.ge5',
 'park_ss_ff_hedm_resolution_0MPa_unload_000673.edf.ge5': 'dark_before_000675.edf.ge5',
 'park_ss_ff_230MPa_000425.edf.ge5': 'dark_before_000428.edf.ge5',
 'park_ss_ff_270MPa_000517.edf.ge5': 'dark_before_000523.edf.ge5',
 'park_ss_ff_0MPa_

In [7]:
len(darkFilesDict4Idx)

261

In [8]:
# now start to convert ge5 files to patches
from src.datasets.ge2patch import *

In [9]:
outDir = '../park_ff_patch_dir/'

i = 1

for key in darkFilesDict4Idx:
    print(f"Reading dark file from {dataDir+darkFilesDict4Idx[key]} ... ")
    dark = ge_raw2array(dataDir+darkFilesDict4Idx[key], skip_frm=0).mean(axis=0).astype(np.float32)
    print(f"Done with reading dark file from {dataDir+darkFilesDict4Idx[key]} with {dark}")
    print(f"The input file is {key}")
    outFile = outDir + key[:-3] + "h5"
    print(f"The output file is {outFile}")
    print(f"Start to generate patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    ge_raw2patch(gefname=dataDir+key, ofn=outFile, dark=dark, 
                 bkgd=100, psz=15, skip_frm=0, min_intensity=0, max_r=None)
    print(f"Done generating patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    i += 1

Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000633.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000633.edf.ge5 with [[1649.2 1659.5 1658.7 ... 1834.5 1833.1 1830. ]
 [1668.6 1674.5 1672.7 ... 1825.9 1824.  1824. ]
 [1678.7 1682.7 1680.4 ... 1833.6 1834.9 1831.2]
 ...
 [1678.8 1681.1 1680.7 ... 1736.2 1734.9 1734.3]
 [1672.5 1670.9 1673.6 ... 1730.9 1730.8 1726.9]
 [1635.8 1635.  1633.8 ... 1701.1 1699.7 1699.6]]
The input file is park_ss_ff_90MPa_unload_000631.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_90MPa_unload_000631.edf.h5
Start to generate patches for file park_ss_ff_90MPa_unload_000631.edf.ge5 (1/261)...
203500 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_90MPa_unload_000631.edf.ge5, 3333 are too big.
Done generating patches for file park_ss_ff_90MPa_unload_000631.edf.ge5 (1/261)...
Reading dark file from /

2726 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_000269.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_000269.edf.ge5 (9/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000398.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000398.edf.ge5 with [[1649.7 1658.5 1658.  ... 1834.6 1832.6 1829.5]
 [1668.3 1674.5 1672.8 ... 1825.7 1824.7 1822.8]
 [1677.6 1683.2 1679.7 ... 1833.5 1833.7 1831. ]
 ...
 [1680.  1680.6 1680.8 ... 1736.4 1735.9 1734.2]
 [1673.  1669.8 1672.5 ... 1730.7 1730.6 1728.2]
 [1635.7 1635.2 1633.7 ... 1700.9 1700.5 1699.9]]
The input file is park_ss_ff_100MPa_000396.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_100MPa_000396.edf.h5
Start to generate patches for file park_ss_ff_100MPa_000396.edf.ge5 (10/261)...
44853 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_da

10970 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_0MPa_000341.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_0MPa_000341.edf.ge5 (18/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000434.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000434.edf.ge5 with [[1649.7 1658.1 1658.3 ... 1834.4 1833.2 1829.7]
 [1669.  1674.6 1673.4 ... 1825.6 1823.8 1823.4]
 [1677.9 1682.6 1679.5 ... 1832.8 1834.3 1831.3]
 ...
 [1678.8 1680.1 1681.4 ... 1735.9 1735.7 1734.5]
 [1671.9 1671.4 1673.  ... 1730.4 1731.  1727.4]
 [1636.3 1636.3 1633.3 ... 1700.7 1700.  1699.7]]
The input file is park_ss_ff_235MPa_000431.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_235MPa_000431.edf.h5
Start to generate patches for file park_ss_ff_235MPa_000431.edf.ge5 (19/261)...
43828 patches of size 15 cropped from /net/wolf/data/tomo1/p

6333 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_000260.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_000260.edf.ge5 (27/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000467.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000467.edf.ge5 with [[1649.5 1659.  1658.5 ... 1835.1 1832.6 1829.2]
 [1669.4 1674.2 1674.  ... 1826.3 1823.8 1823.4]
 [1678.1 1683.2 1680.5 ... 1833.2 1834.2 1832.1]
 ...
 [1679.2 1680.4 1681.  ... 1735.9 1735.3 1734.6]
 [1672.9 1670.5 1673.3 ... 1730.1 1731.1 1726.7]
 [1635.9 1635.7 1633.7 ... 1701.1 1700.7 1700.3]]
The input file is park_ss_ff_250MPa_000462.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_250MPa_000462.edf.h5
Start to generate patches for file park_ss_ff_250MPa_000462.edf.ge5 (28/261)...
43820 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_d

46278 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_0MPa_000316.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_0MPa_000316.edf.ge5 (36/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000561.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000561.edf.ge5 with [[1649.1 1658.7 1658.8 ... 1834.7 1832.9 1829.8]
 [1668.1 1674.8 1672.2 ... 1825.4 1824.6 1823.4]
 [1678.4 1682.3 1680.2 ... 1833.7 1834.8 1831.5]
 ...
 [1679.4 1680.5 1681.7 ... 1736.4 1735.8 1734.3]
 [1672.4 1670.3 1671.9 ... 1730.2 1731.3 1727. ]
 [1635.8 1635.8 1633.9 ... 1701.  1699.1 1699.9]]
The input file is park_ss_ff_290MPa_000556.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_290MPa_000556.edf.h5
Start to generate patches for file park_ss_ff_290MPa_000556.edf.ge5 (37/261)...
143642 patches of size 15 cropped from /net/wolf/data/tomo1/

14377 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_hedm_resolution_0MPa_unload_000658.edf.ge5, 9 are too big.
Done generating patches for file park_ss_ff_hedm_resolution_0MPa_unload_000658.edf.ge5 (45/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000320.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000320.edf.ge5 with [[1650.  1658.3 1656.7 ... 1834.6 1833.4 1829.5]
 [1669.9 1674.9 1672.5 ... 1825.7 1823.8 1823.2]
 [1678.2 1682.4 1679.8 ... 1834.1 1833.8 1830.6]
 ...
 [1678.5 1679.1 1681.8 ... 1736.2 1736.3 1734.8]
 [1672.6 1670.8 1673.  ... 1730.7 1730.  1726.8]
 [1635.5 1635.6 1633.9 ... 1701.5 1700.3 1699.2]]
The input file is park_ss_ff_0MPa_000315.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_0MPa_000315.edf.h5
Start to generate patches for file park_ss_ff_0MPa_000315.edf.ge5 (46/261)...
47697 patches of siz

101326 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_hedm_resolution_0MPa_unload_000676.edf.ge5, 849 are too big.
Done generating patches for file park_ss_ff_hedm_resolution_0MPa_unload_000676.edf.ge5 (54/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000383.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000383.edf.ge5 with [[1649.2 1657.7 1659.1 ... 1834.6 1833.6 1830. ]
 [1669.2 1673.8 1672.2 ... 1825.5 1824.7 1823.4]
 [1677.9 1682.5 1679.6 ... 1833.  1833.9 1831. ]
 ...
 [1678.7 1681.  1681.4 ... 1736.  1735.5 1735.1]
 [1672.2 1671.  1672.2 ... 1731.  1731.3 1727.2]
 [1635.8 1636.4 1632.9 ... 1700.9 1700.  1700. ]]
The input file is park_ss_ff_50MPa_000378.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_50MPa_000378.edf.h5
Start to generate patches for file park_ss_ff_50MPa_000378.edf.ge5 (55/261)...
47249 patches 

41936 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_250MPa_2_000470.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_250MPa_2_000470.edf.ge5 (63/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000452.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000452.edf.ge5 with [[1649.2 1658.9 1658.6 ... 1834.6 1833.4 1829.5]
 [1668.8 1674.8 1673.9 ... 1825.5 1824.6 1822.8]
 [1678.7 1682.4 1679.4 ... 1834.1 1834.7 1831.4]
 ...
 [1678.8 1680.4 1681.6 ... 1736.  1736.4 1734.5]
 [1672.4 1670.7 1671.6 ... 1730.  1731.3 1726.2]
 [1635.4 1635.6 1633.9 ... 1700.4 1700.2 1700. ]]
The input file is park_ss_ff_hedm_resolution_235MPa_000450.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_hedm_resolution_235MPa_000450.edf.h5
Start to generate patches for file park_ss_ff_hedm_resolution_235MPa_000450.edf.ge5 (64/261)...
2041

13675 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_hedm_resolution_290MPa_000586.edf.ge5, 7 are too big.
Done generating patches for file park_ss_ff_hedm_resolution_290MPa_000586.edf.ge5 (72/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000281.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000281.edf.ge5 with [[1650.3 1658.7 1658.5 ... 1834.1 1833.5 1830. ]
 [1669.  1675.1 1673.  ... 1825.1 1823.5 1823.8]
 [1677.3 1682.3 1679.5 ... 1833.4 1834.  1831. ]
 ...
 [1679.6 1680.5 1680.9 ... 1736.1 1735.8 1735.2]
 [1672.2 1671.1 1671.9 ... 1730.9 1730.7 1727.4]
 [1636.  1635.1 1633.8 ... 1701.  1700.4 1700.1]]
The input file is park_ss_ff_000279.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_000279.edf.h5
Start to generate patches for file park_ss_ff_000279.edf.ge5 (73/261)...
2946 patches of size 15 cropped from /net/wol

20508 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_hedm_resolution_250MPa_2_000480.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_hedm_resolution_250MPa_2_000480.edf.ge5 (81/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000344.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000344.edf.ge5 with [[1650.6 1658.1 1658.2 ... 1835.4 1833.4 1829.4]
 [1669.1 1674.4 1671.7 ... 1825.3 1824.6 1823.7]
 [1678.  1682.9 1679.2 ... 1833.9 1833.8 1831.2]
 ...
 [1678.8 1680.5 1680.7 ... 1736.7 1735.2 1734.1]
 [1672.8 1670.7 1672.4 ... 1730.7 1730.5 1726.6]
 [1635.1 1634.5 1633.6 ... 1700.6 1700.1 1699.6]]
The input file is park_ss_ff_0MPa_000340.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_0MPa_000340.edf.h5
Start to generate patches for file park_ss_ff_0MPa_000340.edf.ge5 (82/261)...
10802 patches of size 15 c

41736 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_250MPa_000463.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_250MPa_000463.edf.ge5 (90/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000440.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000440.edf.ge5 with [[1649.3 1658.4 1658.1 ... 1834.6 1833.2 1829.3]
 [1668.8 1674.7 1672.  ... 1826.1 1824.3 1822.8]
 [1677.9 1682.7 1679.5 ... 1833.1 1834.3 1831.5]
 ...
 [1680.  1680.1 1681.6 ... 1736.8 1735.6 1734.1]
 [1672.7 1670.4 1671.9 ... 1730.2 1730.8 1726.4]
 [1636.  1634.9 1633.8 ... 1701.2 1700.2 1699.1]]
The input file is park_ss_ff_hedm_resolution_235MPa_000438.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_hedm_resolution_235MPa_000438.edf.h5
Start to generate patches for file park_ss_ff_hedm_resolution_235MPa_000438.edf.ge5 (91/261)...
21457 pa

23366 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_0MPa_000325.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_0MPa_000325.edf.ge5 (99/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000329.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000329.edf.ge5 with [[1649.4 1658.5 1658.  ... 1835.1 1832.8 1830.1]
 [1668.6 1673.9 1672.7 ... 1826.4 1824.8 1822.9]
 [1677.8 1683.4 1680.6 ... 1832.6 1833.8 1832. ]
 ...
 [1679.1 1681.5 1681.6 ... 1736.2 1735.2 1733.9]
 [1672.  1670.2 1673.  ... 1730.6 1730.4 1726.5]
 [1635.8 1635.4 1633.6 ... 1700.1 1699.6 1699.4]]
The input file is park_ss_ff_0MPa_000321.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_0MPa_000321.edf.h5
Start to generate patches for file park_ss_ff_0MPa_000321.edf.ge5 (100/261)...
23623 patches of size 15 cropped from /net/wolf/data/tomo1/park_m

2854 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_000274.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_000274.edf.ge5 (108/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000723.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000723.edf.ge5 with [[1649.8 1658.1 1657.7 ... 1835.  1833.1 1829.7]
 [1669.1 1674.7 1672.7 ... 1826.4 1822.9 1822.4]
 [1676.8 1682.3 1680.2 ... 1833.4 1834.8 1831.8]
 ...
 [1679.2 1681.1 1681.3 ... 1736.5 1734.6 1734.8]
 [1672.2 1670.8 1672.1 ... 1731.2 1731.  1727.4]
 [1636.  1635.7 1633.8 ... 1700.1 1699.5 1700.1]]
The input file is park_ss_ff_ome_offset_0MPa_unload_000721.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_ome_offset_0MPa_unload_000721.edf.h5
Start to generate patches for file park_ss_ff_ome_offset_0MPa_unload_000721.edf.ge5 (109/261)...
227497 patches of siz

192048 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_290MPa_000562.edf.ge5, 2872 are too big.
Done generating patches for file park_ss_ff_290MPa_000562.edf.ge5 (117/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000434.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000434.edf.ge5 with [[1649.7 1658.1 1658.3 ... 1834.4 1833.2 1829.7]
 [1669.  1674.6 1673.4 ... 1825.6 1823.8 1823.4]
 [1677.9 1682.6 1679.5 ... 1832.8 1834.3 1831.3]
 ...
 [1678.8 1680.1 1681.4 ... 1735.9 1735.7 1734.5]
 [1671.9 1671.4 1673.  ... 1730.4 1731.  1727.4]
 [1636.3 1636.3 1633.3 ... 1700.7 1700.  1699.7]]
The input file is park_ss_ff_235MPa_000430.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_235MPa_000430.edf.h5
Start to generate patches for file park_ss_ff_235MPa_000430.edf.ge5 (118/261)...
42651 patches of size 15 cropped from /net/wolf/da

37532 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff2_000289.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff2_000289.edf.ge5 (126/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000600.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000600.edf.ge5 with [[1649.8 1657.7 1658.3 ... 1835.3 1833.5 1829.5]
 [1669.1 1674.5 1672.  ... 1825.9 1824.3 1823.1]
 [1678.3 1683.2 1680.2 ... 1833.2 1834.5 1832. ]
 ...
 [1679.1 1681.  1681.9 ... 1735.6 1736.1 1735.2]
 [1672.8 1669.7 1671.6 ... 1730.2 1731.3 1726.9]
 [1635.5 1635.1 1634.1 ... 1700.8 1700.3 1700. ]]
The input file is park_ss_ff_hedm_resolution_290MPa_000598.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_hedm_resolution_290MPa_000598.edf.h5
Start to generate patches for file park_ss_ff_hedm_resolution_290MPa_000598.edf.ge5 (127/261)...
108019 patches of 

203647 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_0MPa_unload_000642.edf.ge5, 2822 are too big.
Done generating patches for file park_ss_ff_0MPa_unload_000642.edf.ge5 (135/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000344.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000344.edf.ge5 with [[1650.6 1658.1 1658.2 ... 1835.4 1833.4 1829.4]
 [1669.1 1674.4 1671.7 ... 1825.3 1824.6 1823.7]
 [1678.  1682.9 1679.2 ... 1833.9 1833.8 1831.2]
 ...
 [1678.8 1680.5 1680.7 ... 1736.7 1735.2 1734.1]
 [1672.8 1670.7 1672.4 ... 1730.7 1730.5 1726.6]
 [1635.1 1634.5 1633.6 ... 1700.6 1700.1 1699.6]]
The input file is park_ss_ff_0MPa_000342.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_0MPa_000342.edf.h5
Start to generate patches for file park_ss_ff_0MPa_000342.edf.ge5 (136/261)...
10788 patches of size 15 cropped from /net/wol

102496 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_hedm_resolution_0MPa_unload_000670.edf.ge5, 893 are too big.
Done generating patches for file park_ss_ff_hedm_resolution_0MPa_unload_000670.edf.ge5 (144/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000398.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000398.edf.ge5 with [[1649.7 1658.5 1658.  ... 1834.6 1832.6 1829.5]
 [1668.3 1674.5 1672.8 ... 1825.7 1824.7 1822.8]
 [1677.6 1683.2 1679.7 ... 1833.5 1833.7 1831. ]
 ...
 [1680.  1680.6 1680.8 ... 1736.4 1735.9 1734.2]
 [1673.  1669.8 1672.5 ... 1730.7 1730.6 1728.2]
 [1635.7 1635.2 1633.7 ... 1700.9 1700.5 1699.9]]
The input file is park_ss_ff_100MPa_000393.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_100MPa_000393.edf.h5
Start to generate patches for file park_ss_ff_100MPa_000393.edf.ge5 (145/261)...
46043 pat

20764 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_hedm_resolution_0MPa_000312.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_hedm_resolution_0MPa_000312.edf.ge5 (153/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000738.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000738.edf.ge5 with [[1649.1 1659.1 1657.1 ... 1834.8 1832.8 1829.8]
 [1668.9 1674.3 1672.7 ... 1825.2 1825.  1823.4]
 [1678.7 1683.1 1679.  ... 1832.9 1834.6 1831.4]
 ...
 [1679.1 1680.6 1680.7 ... 1736.3 1735.8 1734.5]
 [1672.4 1671.2 1672.8 ... 1730.6 1730.8 1726.8]
 [1636.3 1635.6 1633.5 ... 1701.  1699.5 1699.9]]
The input file is park_ss_ff_ome_offset_0MPa_unload_000736.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_ome_offset_0MPa_unload_000736.edf.h5
Start to generate patches for file park_ss_ff_ome_offset_0MPa_unload_000736

21417 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_hedm_resolution_235MPa_000441.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_hedm_resolution_235MPa_000441.edf.ge5 (162/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000615.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000615.edf.ge5 with [[1650.2 1658.5 1657.9 ... 1835.1 1833.1 1830.7]
 [1668.9 1674.9 1673.  ... 1824.9 1823.7 1823.8]
 [1678.1 1683.  1680.6 ... 1833.4 1834.4 1831.5]
 ...
 [1679.8 1680.4 1681.5 ... 1736.3 1735.1 1734.1]
 [1672.7 1670.7 1673.  ... 1730.8 1730.5 1727.9]
 [1635.9 1635.4 1634.4 ... 1701.1 1701.  1699.5]]
The input file is park_ss_ff_190MPa_unload_000613.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_190MPa_unload_000613.edf.h5
Start to generate patches for file park_ss_ff_190MPa_unload_000613.edf.ge5 (163/261)...
3

45310 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_150MPa_000399.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_150MPa_000399.edf.ge5 (171/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000281.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000281.edf.ge5 with [[1650.3 1658.7 1658.5 ... 1834.1 1833.5 1830. ]
 [1669.  1675.1 1673.  ... 1825.1 1823.5 1823.8]
 [1677.3 1682.3 1679.5 ... 1833.4 1834.  1831. ]
 ...
 [1679.6 1680.5 1680.9 ... 1736.1 1735.8 1735.2]
 [1672.2 1671.1 1671.9 ... 1730.9 1730.7 1727.4]
 [1636.  1635.1 1633.8 ... 1701.  1700.4 1700.1]]
The input file is park_ss_ff_000276.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_000276.edf.h5
Start to generate patches for file park_ss_ff_000276.edf.ge5 (172/261)...
2542 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/p

6731 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_000259.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_000259.edf.ge5 (180/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000508.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000508.edf.ge5 with [[1649.7 1658.4 1658.2 ... 1833.8 1832.5 1830.9]
 [1669.7 1674.6 1672.5 ... 1826.5 1824.5 1823.6]
 [1678.4 1683.  1679.8 ... 1833.7 1834.1 1830.8]
 ...
 [1679.8 1680.8 1682.1 ... 1736.5 1735.7 1734.4]
 [1672.7 1670.6 1672.9 ... 1730.8 1731.5 1727. ]
 [1635.1 1635.3 1633.6 ... 1701.1 1699.9 1700.1]]
The input file is park_ss_ff_260MPa_000506.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_260MPa_000506.edf.h5
Start to generate patches for file park_ss_ff_260MPa_000506.edf.ge5 (181/261)...
71787 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22

34564 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_190MPa_unload_000610.edf.ge5, 15 are too big.
Done generating patches for file park_ss_ff_190MPa_unload_000610.edf.ge5 (189/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000287.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000287.edf.ge5 with [[1650.  1658.7 1658.9 ... 1834.1 1833.2 1829.9]
 [1669.  1673.8 1672.1 ... 1825.8 1824.2 1822.7]
 [1677.7 1683.7 1680.7 ... 1833.4 1834.  1831.6]
 ...
 [1679.1 1680.3 1681.7 ... 1736.3 1734.6 1734.8]
 [1672.4 1671.1 1672.6 ... 1730.2 1730.3 1726.8]
 [1636.  1634.4 1634.3 ... 1700.9 1700.3 1700.1]]
The input file is park_ss_ff_000284.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_000284.edf.h5
Start to generate patches for file park_ss_ff_000284.edf.ge5 (190/261)...
71265 patches of size 15 cropped from /net/wolf/data/tomo1/p

31570 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_0MPa_unload_000635.edf.ge5, 30 are too big.
Done generating patches for file park_ss_ff_0MPa_unload_000635.edf.ge5 (198/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000344.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000344.edf.ge5 with [[1650.6 1658.1 1658.2 ... 1835.4 1833.4 1829.4]
 [1669.1 1674.4 1671.7 ... 1825.3 1824.6 1823.7]
 [1678.  1682.9 1679.2 ... 1833.9 1833.8 1831.2]
 ...
 [1678.8 1680.5 1680.7 ... 1736.7 1735.2 1734.1]
 [1672.8 1670.7 1672.4 ... 1730.7 1730.5 1726.6]
 [1635.1 1634.5 1633.6 ... 1700.6 1700.1 1699.6]]
The input file is park_ss_ff_0MPa_000338.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_0MPa_000338.edf.h5
Start to generate patches for file park_ss_ff_0MPa_000338.edf.ge5 (199/261)...
10776 patches of size 15 cropped from /net/wolf/d

Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000251.edf.ge5 with [[1649.6 1658.1 1657.8 ... 1833.5 1832.7 1829.5]
 [1668.2 1674.3 1672.2 ... 1826.2 1823.5 1822.9]
 [1678.  1682.6 1680.  ... 1833.2 1833.4 1831.8]
 ...
 [1680.1 1680.1 1680.9 ... 1736.9 1734.9 1735. ]
 [1672.7 1670.6 1672.5 ... 1730.4 1730.7 1727.6]
 [1634.9 1635.7 1634.6 ... 1700.5 1700.1 1699.6]]
The input file is park_ss_ff_000248.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_000248.edf.h5
Start to generate patches for file park_ss_ff_000248.edf.ge5 (207/261)...
5962 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_000248.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_000248.edf.ge5 (207/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000508.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_

204247 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_190MPa_unload_000619.edf.ge5, 3440 are too big.
Done generating patches for file park_ss_ff_190MPa_unload_000619.edf.ge5 (215/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000627.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000627.edf.ge5 with [[1649.3 1658.2 1658.  ... 1834.9 1833.2 1830.2]
 [1668.6 1673.5 1672.  ... 1825.6 1824.1 1822.8]
 [1678.2 1682.6 1679.  ... 1833.  1833.7 1831.3]
 ...
 [1678.5 1680.2 1681.8 ... 1736.7 1735.1 1733.9]
 [1672.5 1670.6 1672.1 ... 1731.3 1730.4 1726.5]
 [1636.  1635.6 1633.5 ... 1700.8 1700.  1700. ]]
The input file is park_ss_ff_90MPa_unload_000622.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_90MPa_unload_000622.edf.h5
Start to generate patches for file park_ss_ff_90MPa_unload_000622.edf.ge5 (216/261)...
34268 patches of s

29949 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_ome_offset_0MPa_unload_000688.edf.ge5, 31 are too big.
Done generating patches for file park_ss_ff_ome_offset_0MPa_unload_000688.edf.ge5 (224/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000669.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000669.edf.ge5 with [[1649.8 1658.9 1658.  ... 1834.2 1832.4 1829.3]
 [1669.2 1675.4 1673.1 ... 1824.9 1824.2 1823.1]
 [1678.  1682.6 1680.2 ... 1833.7 1834.3 1831.7]
 ...
 [1679.8 1680.7 1681.3 ... 1737.  1735.7 1734.5]
 [1672.8 1671.  1673.1 ... 1730.9 1730.4 1726.6]
 [1635.7 1635.6 1633.8 ... 1700.8 1700.2 1699.5]]
The input file is park_ss_ff_hedm_resolution_0MPa_unload_000667.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_hedm_resolution_0MPa_unload_000667.edf.h5
Start to generate patches for file park_ss_ff_hedm_resolutio

204225 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_190MPa_unload_000617.edf.ge5, 3100 are too big.
Done generating patches for file park_ss_ff_190MPa_unload_000617.edf.ge5 (233/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000523.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000523.edf.ge5 with [[1649.3 1657.8 1658.2 ... 1834.4 1832.7 1829.9]
 [1669.1 1674.9 1672.1 ... 1825.5 1824.2 1822.4]
 [1678.  1683.1 1680.2 ... 1833.8 1834.4 1831.4]
 ...
 [1678.5 1681.  1681.1 ... 1736.9 1735.6 1734.7]
 [1672.6 1669.8 1672.6 ... 1730.  1731.2 1726.6]
 [1635.2 1635.2 1634.5 ... 1701.2 1699.6 1699.2]]
The input file is park_ss_ff_270MPa_000516.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_270MPa_000516.edf.h5
Start to generate patches for file park_ss_ff_270MPa_000516.edf.ge5 (234/261)...
89701 patches of size 15 cropped fro

22255 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_50MPa_000386.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff_50MPa_000386.edf.ge5 (242/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000529.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000529.edf.ge5 with [[1649.6 1657.8 1658.1 ... 1834.7 1833.  1828.8]
 [1668.3 1673.9 1672.1 ... 1825.3 1824.7 1823.9]
 [1677.7 1681.5 1680.8 ... 1833.3 1833.7 1831.8]
 ...
 [1679.4 1680.1 1681.  ... 1735.9 1735.2 1735. ]
 [1672.  1670.5 1672.1 ... 1731.  1731.1 1727.2]
 [1635.7 1635.3 1633.2 ... 1700.9 1700.  1699.6]]
The input file is park_ss_ff_280MPa_000524.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_280MPa_000524.edf.h5
Start to generate patches for file park_ss_ff_280MPa_000524.edf.ge5 (243/261)...
44851 patches of size 15 cropped from /net/wolf/data/tom

44247 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff3_000375.edf.ge5, 0 are too big.
Done generating patches for file park_ss_ff3_000375.edf.ge5 (251/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000555.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000555.edf.ge5 with [[1650.3 1658.1 1658.1 ... 1834.  1832.9 1829.6]
 [1668.9 1674.3 1672.7 ... 1825.2 1824.3 1823.6]
 [1677.5 1682.4 1680.  ... 1834.3 1834.1 1831.8]
 ...
 [1679.2 1680.4 1681.2 ... 1736.3 1735.5 1734.9]
 [1672.5 1670.7 1672.7 ... 1730.4 1731.4 1728.1]
 [1635.6 1635.  1634.2 ... 1700.4 1700.1 1699.2]]
The input file is park_ss_ff_290MPa_000551.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff_290MPa_000551.edf.h5
Start to generate patches for file park_ss_ff_290MPa_000551.edf.ge5 (252/261)...
71457 patches of size 15 cropped from /net/wolf/data/tomo1/park_ma

29666 patches of size 15 cropped from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/park_ss_ff_ome_offset_0MPa_unload_000691.edf.ge5, 34 are too big.
Done generating patches for file park_ss_ff_ome_offset_0MPa_unload_000691.edf.ge5 (260/261)...
Reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000347.edf.ge5 ... 
Done with reading dark file from /net/wolf/data/tomo1/park_mar22_data/park_mar22/ge5/dark_before_000347.edf.ge5 with [[1650.5 1658.6 1658.  ... 1835.  1833.8 1829.1]
 [1668.5 1674.3 1672.2 ... 1826.5 1823.3 1822.3]
 [1678.9 1683.1 1679.3 ... 1833.8 1834.4 1830.4]
 ...
 [1678.6 1679.7 1681.5 ... 1735.9 1735.6 1735. ]
 [1672.2 1669.3 1672.3 ... 1730.7 1730.6 1727.3]
 [1635.6 1635.1 1634.7 ... 1701.  1700.4 1699.3]]
The input file is park_ss_ff3_000345.edf.ge5
The output file is ../park_ff_patch_dir/park_ss_ff3_000345.edf.h5
Start to generate patches for file park_ss_ff3_000345.edf.ge5 (261/261)...
44947 patches of size 15 cropped from /