In [1]:
import os

dataDir = '/home/beams/S1IDUSER/mnt/s1c/sangid_aug19_data/sangid_aug19/ge3/'

listFiles = os.listdir(dataDir)
listFiles

['CeO2_after_lshr_000814.ge3',
 'Au_ff_000221.ge3',
 'Au_ff_000821.ge3',
 'Au_ff_test_000219.ge3',
 'Au_ff_test_000220.ge3',
 'CeO2_2s_000211.ge3',
 'lshr_loading_with_ff_corrected_1_000512.ge3',
 'CeO2_after_lshr_000815.ge3',
 'CeO2_after_lshr_000816.ge3',
 'CeO2_after_lshr_000817.ge3',
 'CeO2_after_lshr_000818.ge3',
 'CeO2_after_lshr_000819.ge3',
 'CeO2_real_2s_000216.ge3',
 'CeO2_real_2s_000217.ge3',
 'CeO2_real_2s_000218.ge3',
 'CeO2_test_2s_000212.ge3',
 'CeO2_test_2s_000213.ge3',
 'CeO2_test_2s_000214.ge3',
 'CeO2_test_2s_000215.ge3',
 'CuWC_line_ff_000474.ge3',
 'CuWC_test_1_000470.ge3',
 'CuWC_test_2_000471.ge3',
 'CuWC_test_3_000472.ge3',
 'dark_0p02s_000222.ge3',
 'ceo2_post_ti7_sample3_nf_hydraz_1218_ramsrot_0_000443.ge3',
 'ceo2_post_ti7_sample3_nf_hydraz_1218_ramsrot_0_real_000447.ge3',
 'ceo2_post_ti7_sample3_nf_hydraz_1218_ramsrot_0_test_1_000444.ge3',
 'ceo2_post_ti7_sample3_nf_hydraz_1218_ramsrot_0_test_2_000445.ge3',
 'ceo2_post_ti7_sample3_nf_hydraz_1218_ramsrot_0_te

In [2]:
darkFilesList = []
darkFilesDict = {}

for fileString in listFiles:
    if fileString.startswith('dark_before'):
        # find the index of each dark before
        idx = int(fileString[12:18])
        #print(int(fileString[12:18]))
        darkFilesDict[idx] = fileString

darkFilesDict

{231: 'dark_before_000231.ge3',
 236: 'dark_before_000236.ge3',
 242: 'dark_before_000242.ge3',
 246: 'dark_before_000246.ge3',
 250: 'dark_before_000250.ge3',
 259: 'dark_before_000259.ge3',
 263: 'dark_before_000263.ge3',
 268: 'dark_before_000268.ge3',
 273: 'dark_before_000273.ge3',
 278: 'dark_before_000278.ge3',
 283: 'dark_before_000283.ge3',
 288: 'dark_before_000288.ge3',
 293: 'dark_before_000293.ge3',
 299: 'dark_before_000299.ge3',
 308: 'dark_before_000308.ge3',
 320: 'dark_before_000320.ge3',
 376: 'dark_before_000376.ge3',
 380: 'dark_before_000380.ge3',
 390: 'dark_before_000390.ge3',
 463: 'dark_before_000463.ge3',
 467: 'dark_before_000467.ge3',
 473: 'dark_before_000473.ge3',
 479: 'dark_before_000479.ge3',
 487: 'dark_before_000487.ge3',
 495: 'dark_before_000495.ge3',
 500: 'dark_before_000500.ge3',
 508: 'dark_before_000508.ge3',
 511: 'dark_before_000511.ge3',
 514: 'dark_before_000514.ge3',
 518: 'dark_before_000518.ge3',
 522: 'dark_before_000522.ge3',
 526: 'd

In [3]:
darkFilesDict

{231: 'dark_before_000231.ge3',
 236: 'dark_before_000236.ge3',
 242: 'dark_before_000242.ge3',
 246: 'dark_before_000246.ge3',
 250: 'dark_before_000250.ge3',
 259: 'dark_before_000259.ge3',
 263: 'dark_before_000263.ge3',
 268: 'dark_before_000268.ge3',
 273: 'dark_before_000273.ge3',
 278: 'dark_before_000278.ge3',
 283: 'dark_before_000283.ge3',
 288: 'dark_before_000288.ge3',
 293: 'dark_before_000293.ge3',
 299: 'dark_before_000299.ge3',
 308: 'dark_before_000308.ge3',
 320: 'dark_before_000320.ge3',
 376: 'dark_before_000376.ge3',
 380: 'dark_before_000380.ge3',
 390: 'dark_before_000390.ge3',
 463: 'dark_before_000463.ge3',
 467: 'dark_before_000467.ge3',
 473: 'dark_before_000473.ge3',
 479: 'dark_before_000479.ge3',
 487: 'dark_before_000487.ge3',
 495: 'dark_before_000495.ge3',
 500: 'dark_before_000500.ge3',
 508: 'dark_before_000508.ge3',
 511: 'dark_before_000511.ge3',
 514: 'dark_before_000514.ge3',
 518: 'dark_before_000518.ge3',
 522: 'dark_before_000522.ge3',
 526: 'd

In [4]:
darkFilesKeys = sorted(darkFilesDict)
darkFilesKeys

[231,
 236,
 242,
 246,
 250,
 259,
 263,
 268,
 273,
 278,
 283,
 288,
 293,
 299,
 308,
 320,
 376,
 380,
 390,
 463,
 467,
 473,
 479,
 487,
 495,
 500,
 508,
 511,
 514,
 518,
 522,
 526,
 530,
 534,
 538,
 542,
 546,
 550,
 554,
 558,
 562,
 566,
 570,
 574,
 578,
 582,
 586,
 590,
 594,
 598,
 602,
 606,
 610,
 614,
 618,
 622,
 626,
 630,
 634,
 638,
 642,
 646,
 650,
 654,
 658,
 662,
 666,
 670,
 674,
 678,
 682,
 686,
 690,
 694,
 698,
 702,
 706,
 710,
 714,
 718,
 722,
 726,
 730,
 734,
 738,
 742,
 746,
 750,
 754,
 758,
 762,
 766,
 770,
 774,
 778,
 782,
 786,
 790,
 794,
 798,
 802,
 806,
 820]

In [5]:
parkFilesList = []
parkFilesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('lshr'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        parkFilesDict4Idx[fileString] = idx
#         idx = int(fileString[12:18])
#         #print(int(fileString[12:18]))
#         darkFilesDict[idx] = fileString
#         darkFiles.append(fileString)

# 
parkFilesDict4Idx 

{'lshr_loading_with_ff_corrected_1_000512.ge3': 512,
 'lshr_loading_with_ff_000509.ge3': 509,
 'lshr_loading_with_ff_000510.ge3': 510,
 'lshr_loading_with_ff_corrected_1_000513.ge3': 513,
 'lshr_loading_with_ff_corrected_2_000515.ge3': 515,
 'lshr_loading_with_ff_corrected_2_000516.ge3': 516,
 'lshr_loading_with_ff_corrected_2_000519.ge3': 519,
 'lshr_loading_with_ff_corrected_2_000520.ge3': 520,
 'lshr_loading_with_ff_corrected_2_000523.ge3': 523,
 'lshr_loading_with_ff_corrected_2_000524.ge3': 524,
 'lshr_loading_with_ff_corrected_2_000527.ge3': 527,
 'lshr_loading_with_ff_corrected_2_000528.ge3': 528,
 'lshr_loading_with_ff_corrected_2_000531.ge3': 531,
 'lshr_loading_with_ff_corrected_2_000532.ge3': 532,
 'lshr_loading_with_ff_corrected_2_000535.ge3': 535,
 'lshr_loading_with_ff_corrected_2_000536.ge3': 536,
 'lshr_loading_with_ff_corrected_2_000539.ge3': 539,
 'lshr_loading_with_ff_corrected_2_000540.ge3': 540,
 'lshr_loading_with_ff_corrected_2_000543.ge3': 543,
 'lshr_loading_wi

In [6]:
# next is to find the dark files for each file
darkFilesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('lshr_'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        # next is to find the corresponding dark file
        for darkKey in darkFilesKeys:
            if darkKey >= idx:
                print(str(idx) + "-" + str(darkKey))
                darkFilesDict4Idx[fileString] = darkFilesDict[darkKey]
                break

darkFilesDict4Idx

512-514
509-511
510-511
513-514
515-518
516-518
519-522
520-522
523-526
524-526
527-530
528-530
531-534
532-534
535-538
536-538
539-542
540-542
543-546
544-546
547-550
548-550
551-554
552-554
555-558
556-558
559-562
560-562
563-566
564-566
567-570
568-570
571-574
572-574
575-578
576-578
579-582
580-582
583-586
584-586
587-590
588-590
591-594
592-594
595-598
596-598
599-602
600-602
603-606
604-606
607-610
608-610
611-614
612-614
615-618
616-618
619-622
620-622
623-626
624-626
627-630
628-630
631-634
632-634
635-638
636-638
639-642
640-642
643-646
644-646
647-650
648-650
651-654
652-654
655-658
656-658
659-662
660-662
663-666
664-666
667-670
668-670
671-674
672-674
675-678
676-678
679-682
680-682
683-686
684-686
687-690
688-690
691-694
692-694
695-698
696-698
699-702
700-702
703-706
704-706
707-710
708-710
711-714
712-714
715-718
716-718
719-722
720-722
723-726
724-726
727-730
728-730
731-734
732-734
735-738
736-738
739-742
740-742
743-746
744-746
747-750
748-750
751-754
752-754
755-758


{'lshr_loading_with_ff_corrected_1_000512.ge3': 'dark_before_000514.ge3',
 'lshr_loading_with_ff_000509.ge3': 'dark_before_000511.ge3',
 'lshr_loading_with_ff_000510.ge3': 'dark_before_000511.ge3',
 'lshr_loading_with_ff_corrected_1_000513.ge3': 'dark_before_000514.ge3',
 'lshr_loading_with_ff_corrected_2_000515.ge3': 'dark_before_000518.ge3',
 'lshr_loading_with_ff_corrected_2_000516.ge3': 'dark_before_000518.ge3',
 'lshr_loading_with_ff_corrected_2_000519.ge3': 'dark_before_000522.ge3',
 'lshr_loading_with_ff_corrected_2_000520.ge3': 'dark_before_000522.ge3',
 'lshr_loading_with_ff_corrected_2_000523.ge3': 'dark_before_000526.ge3',
 'lshr_loading_with_ff_corrected_2_000524.ge3': 'dark_before_000526.ge3',
 'lshr_loading_with_ff_corrected_2_000527.ge3': 'dark_before_000530.ge3',
 'lshr_loading_with_ff_corrected_2_000528.ge3': 'dark_before_000530.ge3',
 'lshr_loading_with_ff_corrected_2_000531.ge3': 'dark_before_000534.ge3',
 'lshr_loading_with_ff_corrected_2_000532.ge3': 'dark_before_0

In [7]:
len(darkFilesDict4Idx)

175

In [8]:
# now start to convert ge5 files to patches
from src.datasets.ge2patch import *

In [9]:
outDir = '../sangid_patch_dir/'

i = 1

for key in darkFilesDict4Idx:
    if i <= 165:
        i += 1
        continue
    print(f"Reading dark file from {dataDir+darkFilesDict4Idx[key]} ... ")
    dark = ge_raw2array(dataDir+darkFilesDict4Idx[key], skip_frm=0).mean(axis=0).astype(np.float32)
    print(f"Done with reading dark file from {dataDir+darkFilesDict4Idx[key]} with {dark}")
    print(f"The input file is {key}")
    outFile = outDir + key[:-3] + "h5"
    print(f"The output file is {outFile}")
    print(f"Start to generate patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    ge_raw2patch(gefname=dataDir+key, ofn=outFile, dark=dark, 
                 bkgd=100, psz=15, skip_frm=0, min_intensity=0, max_r=None)
    print(f"Done generating patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    i += 1

Reading dark file from /home/beams/S1IDUSER/mnt/s1c/sangid_aug19_data/sangid_aug19/ge3/dark_before_000487.ge3 ... 
Done with reading dark file from /home/beams/S1IDUSER/mnt/s1c/sangid_aug19_data/sangid_aug19/ge3/dark_before_000487.ge3 with [[1693.7 1696.2 1695.5 ... 1692.1 1686.5 1682.5]
 [1705.4 1703.4 1707.9 ... 1696.1 1695.5 1696.9]
 [1711.  1710.7 1711.2 ... 1702.5 1698.9 1702.5]
 ...
 [1693.2 1694.7 1694.5 ... 1697.8 1697.2 1696. ]
 [1686.5 1694.8 1691.6 ... 1691.9 1692.4 1689.1]
 [1670.9 1673.6 1674.3 ... 1674.3 1672.4 1670.3]]
The input file is lshr_r1e_state_0_test_4_000486.ge3
The output file is ../sangid_patch_dir/lshr_r1e_state_0_test_4_000486.h5
Start to generate patches for file lshr_r1e_state_0_test_4_000486.ge3 (166/175)...
837 patches of size 15 cropped from /home/beams/S1IDUSER/mnt/s1c/sangid_aug19_data/sangid_aug19/ge3/lshr_r1e_state_0_test_4_000486.ge3, 0 are too big.
Done generating patches for file lshr_r1e_state_0_test_4_000486.ge3 (166/175)...
Reading dark file f