In [1]:
import os

dataDir = '/home/s1c/hurley_feb23/ge5/'

listFiles = os.listdir(dataDir)
listFiles

['test_nugget_al_000019.edf.ge5',
 'CeO2_2s_000013.edf.ge5',
 'CeO2_5s_000014.edf.ge5',
 'nugget_alright_5N_ff_000026.edf.ge5',
 'CeO2_5s_100x100_att000_1600mm_RAMS_000015.edf.ge5',
 'CeO2_5s_100x100_att000_1600mm_RAMS_000016.edf.ge5',
 'dark_CeO2_5s_100x100_att000_1600mm_RAMS_000017.edf.ge5',
 'dark_CeO2_5s_100x100_att000_1600mm_RAMS_000018.edf.ge5',
 'test_nugget_al_000020.edf.ge5',
 'test_nugget_al_000021.edf.ge5',
 'test_nugget_al_000022.edf.ge5',
 'test_nugget_al_000023.edf.ge5',
 'dark_before_000024.edf.ge5',
 'nugget_alright_5N_ff_000027.edf.ge5',
 'nugget_alright_20N_ff_000031.edf.ge5',
 'nugget_alright_5N_ff_000025.edf.ge5',
 'dark_after_000028.edf.ge5',
 'dark_before_000029.edf.ge5',
 'nugget_alright_20N_ff_000032.edf.ge5',
 'nugget_alright_40N_fail_ff_000035.edf.ge5',
 'nugget_alright_20N_ff_000030.edf.ge5',
 'dark_after_000033.edf.ge5',
 'dark_before_000034.edf.ge5',
 'nugget_alright_40N_fail_ff_000036.edf.ge5',
 'nugget_alright_40N_fail_ff_000037.edf.ge5',
 'nugget1_unload

In [2]:
darkFilesList = []
darkFilesDict = {}

for fileString in listFiles:
    if fileString.startswith('dark_before') or fileString.startswith('dark_after'):
        # find the index of each dark before
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        #print(int(fileString[12:18]))
        darkFilesDict[idx] = fileString

darkFilesDict

{24: 'dark_before_000024.edf.ge5',
 28: 'dark_after_000028.edf.ge5',
 29: 'dark_before_000029.edf.ge5',
 33: 'dark_after_000033.edf.ge5',
 34: 'dark_before_000034.edf.ge5',
 38: 'dark_after_000038.edf.ge5',
 45: 'dark_before_000045.edf.ge5',
 47: 'dark_after_000047.edf.ge5',
 51: 'dark_before_000051.edf.ge5',
 55: 'dark_after_000055.edf.ge5',
 56: 'dark_before_000056.edf.ge5',
 60: 'dark_after_000060.edf.ge5',
 61: 'dark_before_000061.edf.ge5',
 65: 'dark_after_000065.edf.ge5',
 66: 'dark_before_000066.edf.ge5',
 70: 'dark_after_000070.edf.ge5',
 71: 'dark_before_000071.edf.ge5',
 75: 'dark_after_000075.edf.ge5',
 81: 'dark_before_000081.edf.ge5',
 87: 'dark_after_000087.edf.ge5',
 88: 'dark_before_000088.edf.ge5',
 94: 'dark_after_000094.edf.ge5',
 95: 'dark_before_000095.edf.ge5',
 101: 'dark_after_000101.edf.ge5',
 102: 'dark_before_000102.edf.ge5',
 108: 'dark_after_000108.edf.ge5',
 109: 'dark_before_000109.edf.ge5',
 115: 'dark_after_000115.edf.ge5',
 116: 'dark_before_000116.edf

In [3]:
darkFilesKeys = sorted(darkFilesDict)
darkFilesKeys

[24,
 28,
 29,
 33,
 34,
 38,
 45,
 47,
 51,
 55,
 56,
 60,
 61,
 65,
 66,
 70,
 71,
 75,
 81,
 87,
 88,
 94,
 95,
 101,
 102,
 108,
 109,
 115,
 116,
 122,
 123,
 129,
 130,
 136]

In [4]:
filesList = []
filesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('nugget1'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        filesDict4Idx[fileString] = idx
#         idx = int(fileString[12:18])
#         #print(int(fileString[12:18]))
#         darkFilesDict[idx] = fileString
#         darkFiles.append(fileString)

# 
filesDict4Idx 

{'nugget1_unload_ff_000053.edf.ge5': 53,
 'nugget1_unload_ff_000054.edf.ge5': 54,
 'nugget1_10N_ff_000058.edf.ge5': 58,
 'nugget1_unload_ff_000052.edf.ge5': 52,
 'nugget1_10N_ff_000059.edf.ge5': 59,
 'nugget1_20N_ff_000063.edf.ge5': 63,
 'nugget1_10N_ff_000057.edf.ge5': 57,
 'nugget1_20N_ff_000064.edf.ge5': 64,
 'nugget1_30N_ff_000068.edf.ge5': 68,
 'nugget1_20N_ff_000062.edf.ge5': 62,
 'nugget1_30N_ff_000069.edf.ge5': 69,
 'nugget1_40N_fail_ff_000073.edf.ge5': 73,
 'nugget1_30N_ff_000067.edf.ge5': 67,
 'nugget1_40N_fail_ff_000074.edf.ge5': 74,
 'nugget1_40N_fail_ff_000072.edf.ge5': 72}

In [5]:
darkFilesDict[darkFilesKeys[0]]

'dark_before_000024.edf.ge5'

In [6]:
# next is to find the dark files for each file
darkFilesDict4Idx = {}

for fileString in listFiles:
    if fileString.startswith('nugget1'):
        # find the index of each file
        
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        # next is to find the corresponding dark file
        prevDark = darkFilesDict[darkFilesKeys[0]]
        for darkKey in darkFilesKeys:
            if darkKey >= idx:
                print(str(idx) + "-" + str(darkKey))
                darkFilesDict4Idx[fileString] = prevDark
                break
            prevDark = darkFilesDict[darkKey]

darkFilesDict4Idx

53-55
54-55
58-60
52-55
59-60
63-65
57-60
64-65
68-70
62-65
69-70
73-75
67-70
74-75
72-75


{'nugget1_unload_ff_000053.edf.ge5': 'dark_before_000051.edf.ge5',
 'nugget1_unload_ff_000054.edf.ge5': 'dark_before_000051.edf.ge5',
 'nugget1_10N_ff_000058.edf.ge5': 'dark_before_000056.edf.ge5',
 'nugget1_unload_ff_000052.edf.ge5': 'dark_before_000051.edf.ge5',
 'nugget1_10N_ff_000059.edf.ge5': 'dark_before_000056.edf.ge5',
 'nugget1_20N_ff_000063.edf.ge5': 'dark_before_000061.edf.ge5',
 'nugget1_10N_ff_000057.edf.ge5': 'dark_before_000056.edf.ge5',
 'nugget1_20N_ff_000064.edf.ge5': 'dark_before_000061.edf.ge5',
 'nugget1_30N_ff_000068.edf.ge5': 'dark_before_000066.edf.ge5',
 'nugget1_20N_ff_000062.edf.ge5': 'dark_before_000061.edf.ge5',
 'nugget1_30N_ff_000069.edf.ge5': 'dark_before_000066.edf.ge5',
 'nugget1_40N_fail_ff_000073.edf.ge5': 'dark_before_000071.edf.ge5',
 'nugget1_30N_ff_000067.edf.ge5': 'dark_before_000066.edf.ge5',
 'nugget1_40N_fail_ff_000074.edf.ge5': 'dark_before_000071.edf.ge5',
 'nugget1_40N_fail_ff_000072.edf.ge5': 'dark_before_000071.edf.ge5'}

In [7]:
# now start to convert ge5 files to patches
from src.datasets.ge2patch import *

In [8]:
import shutil

outDir = '../hurley_feb23_patch_dir_nugget1/'

shutil.rmtree(outDir, ignore_errors=True)
os.makedirs(outDir)


i = 1

for key in darkFilesDict4Idx:
    print(f"Reading dark file from {dataDir+darkFilesDict4Idx[key]} ... ")
    dark = ge_raw2array(dataDir+darkFilesDict4Idx[key], skip_frm=0).mean(axis=0).astype(np.float32)
    print(f"Done with reading dark file from {dataDir+darkFilesDict4Idx[key]} with {dark}")
    print(f"The input file is {key}")
    outFile = outDir + key[:-3] + "h5"
    print(f"The output file is {outFile}")
    print(f"Start to generate patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    ge_raw2patch(gefname=dataDir+key, ofn=outFile, dark=dark, 
                 bkgd=100, psz=15, skip_frm=0, min_intensity=0, max_r=None)
    print(f"Done generating patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    i += 1

Reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000051.edf.ge5 ... 
Done with reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000051.edf.ge5 with [[1691.7 1694.5 1694.4 ... 1688.8 1684.6 1681.9]
 [1703.3 1701.7 1706.2 ... 1695.1 1693.8 1694.2]
 [1709.7 1710.1 1710.3 ... 1701.5 1697.9 1700.6]
 ...
 [1692.8 1693.2 1692.6 ... 1697.5 1695.9 1694.8]
 [1684.6 1692.9 1690.  ... 1690.1 1691.4 1687. ]
 [1666.7 1671.4 1673.3 ... 1673.3 1671.8 1668.6]]
The input file is nugget1_unload_ff_000053.edf.ge5
The output file is ../hurley_feb23_patch_dir_nugget1/nugget1_unload_ff_000053.edf.h5
Start to generate patches for file nugget1_unload_ff_000053.edf.ge5 (1/15)...
425330 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/nugget1_unload_ff_000053.edf.ge5, 49285 are too big.
Done generating patches for file nugget1_unload_ff_000053.edf.ge5 (1/15)...
Reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000051.edf.ge5 ... 
Done with reading dark file from /h

296195 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/nugget1_20N_ff_000062.edf.ge5, 45767 are too big.
Done generating patches for file nugget1_20N_ff_000062.edf.ge5 (10/15)...
Reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000066.edf.ge5 ... 
Done with reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000066.edf.ge5 with [[1692.7 1696.2 1695.  ... 1689.1 1684.9 1682.8]
 [1703.9 1701.5 1707.2 ... 1695.7 1693.7 1695. ]
 [1710.4 1710.1 1710.  ... 1701.5 1697.3 1701.5]
 ...
 [1692.5 1693.7 1693.3 ... 1697.4 1695.4 1695.6]
 [1684.8 1693.2 1689.8 ... 1691.  1690.7 1686.7]
 [1667.2 1672.6 1673.9 ... 1673.1 1670.7 1669.4]]
The input file is nugget1_30N_ff_000069.edf.ge5
The output file is ../hurley_feb23_patch_dir_nugget1/nugget1_30N_ff_000069.edf.h5
Start to generate patches for file nugget1_30N_ff_000069.edf.ge5 (11/15)...
325805 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/nugget1_30N_ff_000069.edf.ge5, 46342 are too big.
Done generatin