In [1]:
import os

dataDir = '/home/s1c/hurley_feb23/ge5/'

listFiles = os.listdir(dataDir)
listFiles

['test_nugget_al_000019.edf.ge5',
 'CeO2_2s_000013.edf.ge5',
 'CeO2_5s_000014.edf.ge5',
 'nugget_alright_5N_ff_000026.edf.ge5',
 'CeO2_5s_100x100_att000_1600mm_RAMS_000015.edf.ge5',
 'CeO2_5s_100x100_att000_1600mm_RAMS_000016.edf.ge5',
 'dark_CeO2_5s_100x100_att000_1600mm_RAMS_000017.edf.ge5',
 'dark_CeO2_5s_100x100_att000_1600mm_RAMS_000018.edf.ge5',
 'test_nugget_al_000020.edf.ge5',
 'test_nugget_al_000021.edf.ge5',
 'test_nugget_al_000022.edf.ge5',
 'test_nugget_al_000023.edf.ge5',
 'dark_before_000024.edf.ge5',
 'nugget_alright_5N_ff_000027.edf.ge5',
 'nugget_alright_20N_ff_000031.edf.ge5',
 'nugget_alright_5N_ff_000025.edf.ge5',
 'dark_after_000028.edf.ge5',
 'dark_before_000029.edf.ge5',
 'nugget_alright_20N_ff_000032.edf.ge5',
 'nugget_alright_40N_fail_ff_000035.edf.ge5',
 'nugget_alright_20N_ff_000030.edf.ge5',
 'dark_after_000033.edf.ge5',
 'dark_before_000034.edf.ge5',
 'nugget_alright_40N_fail_ff_000036.edf.ge5',
 'nugget_alright_40N_fail_ff_000037.edf.ge5',
 'nugget1_unload

In [2]:
darkFilesList = []
darkFilesDict = {}

for fileString in listFiles:
    if fileString.startswith('dark_before') or fileString.startswith('dark_after'):
        # find the index of each dark before
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        #print(int(fileString[12:18]))
        darkFilesDict[idx] = fileString

darkFilesDict

{24: 'dark_before_000024.edf.ge5',
 28: 'dark_after_000028.edf.ge5',
 29: 'dark_before_000029.edf.ge5',
 33: 'dark_after_000033.edf.ge5',
 34: 'dark_before_000034.edf.ge5',
 38: 'dark_after_000038.edf.ge5',
 45: 'dark_before_000045.edf.ge5',
 47: 'dark_after_000047.edf.ge5',
 51: 'dark_before_000051.edf.ge5',
 55: 'dark_after_000055.edf.ge5',
 56: 'dark_before_000056.edf.ge5',
 60: 'dark_after_000060.edf.ge5',
 61: 'dark_before_000061.edf.ge5',
 65: 'dark_after_000065.edf.ge5',
 66: 'dark_before_000066.edf.ge5',
 70: 'dark_after_000070.edf.ge5',
 71: 'dark_before_000071.edf.ge5',
 75: 'dark_after_000075.edf.ge5',
 81: 'dark_before_000081.edf.ge5',
 87: 'dark_after_000087.edf.ge5',
 88: 'dark_before_000088.edf.ge5',
 94: 'dark_after_000094.edf.ge5',
 95: 'dark_before_000095.edf.ge5',
 101: 'dark_after_000101.edf.ge5',
 102: 'dark_before_000102.edf.ge5',
 108: 'dark_after_000108.edf.ge5',
 109: 'dark_before_000109.edf.ge5',
 115: 'dark_after_000115.edf.ge5',
 116: 'dark_before_000116.edf

In [3]:
darkFilesKeys = sorted(darkFilesDict)
darkFilesKeys

[24,
 28,
 29,
 33,
 34,
 38,
 45,
 47,
 51,
 55,
 56,
 60,
 61,
 65,
 66,
 70,
 71,
 75,
 81,
 87,
 88,
 94,
 95,
 101,
 102,
 108,
 109,
 115,
 116,
 122,
 123,
 129,
 130,
 136]

In [4]:
filesList = []
filesDict4Idx = {}

# park_ss_ff

for fileString in listFiles:
    if fileString.startswith('crab'):
        # find the index of each file
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        filesDict4Idx[fileString] = idx
#         idx = int(fileString[12:18])
#         #print(int(fileString[12:18]))
#         darkFilesDict[idx] = fileString
#         darkFiles.append(fileString)

# 
filesDict4Idx 

{'crab_orchard1_unload_ff_000083.edf.ge5': 83,
 'crab_orchard1_unload_ff_000084.edf.ge5': 84,
 'crab_orchard1_unload_ff_000085.edf.ge5': 85,
 'crab_orchard1_unload_ff_000086.edf.ge5': 86,
 'crab_orchard1_10N_ff_000090.edf.ge5': 90,
 'crab_orchard1_unload_ff_000082.edf.ge5': 82,
 'crab_orchard1_10N_ff_000091.edf.ge5': 91,
 'crab_orchard1_10N_ff_000092.edf.ge5': 92,
 'crab_orchard1_10N_ff_000093.edf.ge5': 93,
 'crab_orchard1_20N_ff_000097.edf.ge5': 97,
 'crab_orchard1_10N_ff_000089.edf.ge5': 89,
 'crab_orchard1_20N_ff_000098.edf.ge5': 98,
 'crab_orchard1_20N_ff_000099.edf.ge5': 99,
 'crab_orchard1_20N_ff_000100.edf.ge5': 100,
 'crab_orchard1_20N_ff_000096.edf.ge5': 96,
 'crab_orchard1_30N_ff_000104.edf.ge5': 104,
 'crab_orchard1_30N_ff_000105.edf.ge5': 105,
 'crab_orchard1_30N_ff_000107.edf.ge5': 107,
 'crab_orchard1_30N_ff_000103.edf.ge5': 103,
 'crab_orchard1_40N_ff_000111.edf.ge5': 111,
 'crab_orchard1_30N_ff_000106.edf.ge5': 106,
 'crab_orchard1_40N_ff_000112.edf.ge5': 112,
 'crab_or

In [5]:
darkFilesDict[darkFilesKeys[0]]

'dark_before_000024.edf.ge5'

In [6]:
# next is to find the dark files for each file
darkFilesDict4Idx = {}

for fileString in listFiles:
    if fileString.startswith('crab'):
        # find the index of each file
        
        x = fileString.split("_")
        idx = int(x[-1].split(".")[0])
        # next is to find the corresponding dark file
        prevDark = darkFilesDict[darkFilesKeys[0]]
        for darkKey in darkFilesKeys:
            if darkKey >= idx:
                print(str(idx) + "-" + str(darkKey))
                darkFilesDict4Idx[fileString] = prevDark
                break
            prevDark = darkFilesDict[darkKey]

darkFilesDict4Idx

83-87
84-87
85-87
86-87
90-94
82-87
91-94
92-94
93-94
97-101
89-94
98-101
99-101
100-101
96-101
104-108
105-108
107-108
103-108
111-115
106-108
112-115
113-115
118-122
110-115
114-115
119-122
120-122
121-122
125-129
117-122
126-129
127-129
128-129
132-136
124-129
133-136
134-136
135-136
131-136


{'crab_orchard1_unload_ff_000083.edf.ge5': 'dark_before_000081.edf.ge5',
 'crab_orchard1_unload_ff_000084.edf.ge5': 'dark_before_000081.edf.ge5',
 'crab_orchard1_unload_ff_000085.edf.ge5': 'dark_before_000081.edf.ge5',
 'crab_orchard1_unload_ff_000086.edf.ge5': 'dark_before_000081.edf.ge5',
 'crab_orchard1_10N_ff_000090.edf.ge5': 'dark_before_000088.edf.ge5',
 'crab_orchard1_unload_ff_000082.edf.ge5': 'dark_before_000081.edf.ge5',
 'crab_orchard1_10N_ff_000091.edf.ge5': 'dark_before_000088.edf.ge5',
 'crab_orchard1_10N_ff_000092.edf.ge5': 'dark_before_000088.edf.ge5',
 'crab_orchard1_10N_ff_000093.edf.ge5': 'dark_before_000088.edf.ge5',
 'crab_orchard1_20N_ff_000097.edf.ge5': 'dark_before_000095.edf.ge5',
 'crab_orchard1_10N_ff_000089.edf.ge5': 'dark_before_000088.edf.ge5',
 'crab_orchard1_20N_ff_000098.edf.ge5': 'dark_before_000095.edf.ge5',
 'crab_orchard1_20N_ff_000099.edf.ge5': 'dark_before_000095.edf.ge5',
 'crab_orchard1_20N_ff_000100.edf.ge5': 'dark_before_000095.edf.ge5',
 'cra

In [7]:
# now start to convert ge5 files to patches
from src.datasets.ge2patch import *

In [8]:
import shutil

outDir = '../hurley_feb23_patch_dir_crab/'

shutil.rmtree(outDir, ignore_errors=True)
os.makedirs(outDir)


i = 1

for key in darkFilesDict4Idx:
    print(f"Reading dark file from {dataDir+darkFilesDict4Idx[key]} ... ")
    dark = ge_raw2array(dataDir+darkFilesDict4Idx[key], skip_frm=0).mean(axis=0).astype(np.float32)
    print(f"Done with reading dark file from {dataDir+darkFilesDict4Idx[key]} with {dark}")
    print(f"The input file is {key}")
    outFile = outDir + key[:-3] + "h5"
    print(f"The output file is {outFile}")
    print(f"Start to generate patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    ge_raw2patch(gefname=dataDir+key, ofn=outFile, dark=dark, 
                 bkgd=100, psz=15, skip_frm=0, min_intensity=0, max_r=None)
    print(f"Done generating patches for file {key} ({i}/{len(darkFilesDict4Idx)})...")
    i += 1

Reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000081.edf.ge5 ... 
Done with reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000081.edf.ge5 with [[1693.4 1695.8 1695.9 ... 1689.8 1686.7 1682.7]
 [1704.  1702.  1707.5 ... 1695.6 1693.5 1695.5]
 [1709.5 1710.3 1710.2 ... 1701.7 1697.5 1702. ]
 ...
 [1692.6 1693.4 1692.4 ... 1697.6 1695.7 1695.7]
 [1685.3 1693.6 1690.6 ... 1690.9 1691.2 1687. ]
 [1668.2 1672.3 1673.4 ... 1673.7 1670.9 1669. ]]
The input file is crab_orchard1_unload_ff_000083.edf.ge5
The output file is ../hurley_feb23_patch_dir_crab/crab_orchard1_unload_ff_000083.edf.h5
Start to generate patches for file crab_orchard1_unload_ff_000083.edf.ge5 (1/40)...
3409856 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/crab_orchard1_unload_ff_000083.edf.ge5, 578334 are too big.
Done generating patches for file crab_orchard1_unload_ff_000083.edf.ge5 (1/40)...
Reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000081.edf.ge5 ... 
Done w

Done with reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000095.edf.ge5 with [[1692.6 1695.5 1695.3 ... 1689.  1685.7 1681.8]
 [1704.  1701.7 1707.3 ... 1695.1 1692.8 1695.2]
 [1709.8 1710.9 1710.5 ... 1701.3 1698.  1700.8]
 ...
 [1693.2 1694.  1692.9 ... 1697.  1695.9 1694.5]
 [1684.7 1693.4 1690.  ... 1690.8 1690.9 1687.3]
 [1668.3 1672.6 1673.6 ... 1673.1 1671.3 1668.2]]
The input file is crab_orchard1_20N_ff_000097.edf.ge5
The output file is ../hurley_feb23_patch_dir_crab/crab_orchard1_20N_ff_000097.edf.h5
Start to generate patches for file crab_orchard1_20N_ff_000097.edf.ge5 (10/40)...
3222983 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/crab_orchard1_20N_ff_000097.edf.ge5, 548949 are too big.
Done generating patches for file crab_orchard1_20N_ff_000097.edf.ge5 (10/40)...
Reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000088.edf.ge5 ... 
Done with reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000088.edf.ge5 with [[1692.9 

2979343 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/crab_orchard1_30N_ff_000103.edf.ge5, 510856 are too big.
Done generating patches for file crab_orchard1_30N_ff_000103.edf.ge5 (19/40)...
Reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000109.edf.ge5 ... 
Done with reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000109.edf.ge5 with [[1693.  1694.6 1695.4 ... 1688.3 1685.9 1682.4]
 [1703.4 1702.  1707.  ... 1695.3 1694.  1695.3]
 [1709.1 1709.8 1710.2 ... 1701.9 1697.3 1701.5]
 ...
 [1692.3 1693.6 1693.4 ... 1697.2 1695.8 1694.8]
 [1684.4 1693.7 1690.1 ... 1690.7 1691.3 1686.5]
 [1668.4 1672.9 1673.  ... 1672.9 1671.4 1669.5]]
The input file is crab_orchard1_40N_ff_000111.edf.ge5
The output file is ../hurley_feb23_patch_dir_crab/crab_orchard1_40N_ff_000111.edf.h5
Start to generate patches for file crab_orchard1_40N_ff_000111.edf.ge5 (20/40)...
3709591 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/crab_orchard1_40N_ff_000111.edf.ge

Done generating patches for file crab_orchard1_50N_ff_000120.edf.ge5 (28/40)...
Reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000116.edf.ge5 ... 
Done with reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000116.edf.ge5 with [[1692.  1695.6 1695.1 ... 1689.2 1685.3 1682.5]
 [1703.8 1701.9 1707.8 ... 1695.8 1693.2 1695.2]
 [1709.4 1709.5 1711.1 ... 1701.5 1697.7 1701.5]
 ...
 [1692.9 1693.2 1693.2 ... 1697.7 1696.9 1695.4]
 [1684.8 1694.  1689.9 ... 1691.9 1692.2 1686.8]
 [1668.  1672.7 1673.9 ... 1673.3 1670.8 1668.9]]
The input file is crab_orchard1_50N_ff_000121.edf.ge5
The output file is ../hurley_feb23_patch_dir_crab/crab_orchard1_50N_ff_000121.edf.h5
Start to generate patches for file crab_orchard1_50N_ff_000121.edf.ge5 (29/40)...
2989755 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/crab_orchard1_50N_ff_000121.edf.ge5, 579965 are too big.
Done generating patches for file crab_orchard1_50N_ff_000121.edf.ge5 (29/40)...
Reading dark file fro

2339705 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/crab_orchard1_90N_fail_ff_000134.edf.ge5, 404648 are too big.
Done generating patches for file crab_orchard1_90N_fail_ff_000134.edf.ge5 (38/40)...
Reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000130.edf.ge5 ... 
Done with reading dark file from /home/s1c/hurley_feb23/ge5/dark_before_000130.edf.ge5 with [[1691.8 1695.2 1695.8 ... 1689.1 1686.1 1683.3]
 [1703.6 1701.5 1707.6 ... 1696.5 1693.4 1695.5]
 [1709.9 1709.8 1710.9 ... 1700.8 1697.5 1701.5]
 ...
 [1692.8 1693.7 1692.5 ... 1698.5 1695.9 1695.8]
 [1684.9 1694.1 1689.6 ... 1690.8 1691.7 1687.4]
 [1667.5 1672.7 1673.4 ... 1673.  1670.8 1668.2]]
The input file is crab_orchard1_90N_fail_ff_000135.edf.ge5
The output file is ../hurley_feb23_patch_dir_crab/crab_orchard1_90N_fail_ff_000135.edf.h5
Start to generate patches for file crab_orchard1_90N_fail_ff_000135.edf.ge5 (39/40)...
2412147 patches of size 15 cropped from /home/s1c/hurley_feb23/ge5/crab_orch